### ISSUE TITLE
Huntsman Elite - Strange Behaviour

### ISSUE THREAD

**Issue by SalihBorucu** [1kc/razer-macos#100]
Hello,
!!First of all I would like to agree with one of the issues that stated you being a legend!!

I am receiving some weird behaviour on my Razer Huntsman Elite with Catalina on MBP 13 - 2019, tried both on 0.2.9 and 0.2.8.

I would love to be a part of this project yet my knowledge of electron/react is rather weak atm, if there isn't an easy solution for this, with time I will make sure to have a play around and hopefully provide a PR.

The spectrum starts cycling as normal when the keyboard is plugged in (with the correct profile) and the device is clearly ackowledged as per the image.
![image](https://user-images.githubusercontent.com/56773461/100233220-587dd580-2f21-11eb-87bd-dcde4bc7b84c.png)

- Unfortunately the effects don't seem to do anything for me at all, however when I select "Spectrum All Devices" the spectrum speeds up.

- Only after this fast-spectrum is achieved when I try to add an effect, whatever the color was on at the time of adding effect, it stays as the static color.

This somewhat makes me happy since all I want is static red these days, however I would love to understand if I am doing something wrong and also if anybody else is experiencing the same issue?

Thanks for all your hard work, supporting Razer fans with Macs

**Comment by 1kc** [comment]
Hi Sahil👋 ! Have you tried switching the keyboard profile first before changing the effects? To do this press the combination of these two keys ![Screen Shot 2020-11-25 at 11 59 25 pm](https://user-images.githubusercontent.com/20840688/100237159-43816080-2f7a-11eb-9e0c-cbd6c29ef27c.png)
This usually does the trick

**Comment by SalihBorucu** [comment]
Yeah I did, I am able to toggle between profiles but none of them respond to the effects unfortunately.
There are a few areas which I think I might have done differently to others let me know if you think these could have an effect.

-I have set up profiles on synapse 3 on a windows machine before ( so may be my onboard memory wont let me? )
-Installed/uninstalled synapse 2 and razer drivers on the mbp

**Comment by 1kc** [comment]
Maybe Synapse 2 is conflicting with the app?
I have the non-Elite Huntsman and it works fine.

On 26 Nov 2020, at 12:11 am, Salih <notifications@github.com> wrote:

﻿

Yeah I did, I am able to toggle between profiles but none of them respond to the effects unfortunately.
There are a few areas which I think I might have done differently to others let me know if you think these could have an effect.

-I have set up profiles on synapse 3 on a windows machine before ( so may be my onboard memory wont let me? )
-Installed/uninstalled synapse 2 and razer drivers on the mbp

**Comment by sourav-dey** [comment]
Hi @SalihBorucu ,
If you are referring to save color from synapse 3 to onboard memory, it doesn't.
Have a look at this: https://www.reddit.com/r/razer/comments/a926qz/huntsman_elite_is_there_a_way_that_i_can_attach/

**Comment by SalihBorucu** [comment]
That was what I was referring you are right. I do remember reading this post however, I also have discovered a different behaviour the keyboard has right after reading this post:
- if you disconnect the keyboard while on a static color from Linux or Windows then connect to a macbook it remembers your choice. (it is important that the system isn't shut before you make the transfer otherwise it remembers your last choice as no-lights)
Therefore my assumption was that somewhere somehow the onboard memory has my last choice of color registered, what do you think?

**Comment by SalihBorucu** [comment]
Heya, today I had a chance to try again and it seems everything is working absolutely fine. No idea at all as to what I have changed in the meantime but it is nice and smooth now :)) Once again thank you so much for taking the time to make this. I will close this issue.
