### ISSUE TITLE
Dpi slider needs to have correct values

### ISSUE THREAD

**Issue by sourav-dey** [1kc/razer-macos#102]
The latest DPI slider is awesome, but for mouse like Basilisk Ultimate, it has a max DPI of 20K.
Looks like the slider ends at 16K. 
Can we fix it so that only for Basilisk Ultimate, it goes upto 20K.

**Comment by 1kc** [comment]
@sourav-dey Give this a go https://github.com/1kc/razer-macos/releases/tag/v0.3.0

**Comment by sourav-dey** [comment]
Works fine. Thanks
