### ISSUE TITLE
Huntsman Mini support

### ISSUE THREAD

**Issue by ivancernja** [1kc/razer-macos#107]
Great job building this, first of all.

My Huntsman Mini doesn't get detected even after numerous refreshes. I'm running Mojave.

Please advise.

**Comment by 1kc** [comment]
Hi! Thanks! It seems like the Huntsman mini is unfortunately still a work in progress upstream. (See: https://github.com/openrazer/openrazer/issues/1230) We still have a bit of trouble supporting it after a few tries.

**Comment by ivancernja** [comment]
@1kc Ah, sorry for not digging deeper earlier. 
I might try to jump in and see if I have any luck.

Thanks for the quick reply!

**Comment by sourav-dey** [comment]
Hey @ivancernja ,
Can you please pull https://github.com/1kc/razer-macos/pull/83 and check if you can make it work.

I think, for huntsman mini there is a different transaction id.
Can you just put the case statement under transaction ids and see which one works.

Unfortunately I don't have the device, so if I do, I have to ask someone else to test it.

Please let me know if you need any help.

Thanks,
Sourav

**Comment by ivancernja** [comment]
@sourav-dey I didn't manage to get it working although, that might be due to my lack of knowledge.

Here is info about the Mini:
Razer Huntsman Mini@14230000  <class AppleUSBDevice, id 0x100317ce5, registered, matched, active, busy 0 (15 ms), retain 37>
          {
            "sessionID" = 174840967595377
            "idProduct" = 599
            "iManufacturer" = 1
            "bDeviceClass" = 0
            "bMaxPacketSize0" = 64
            "bcdDevice" = 512
            "iProduct" = 2
            "iSerialNumber" = 3
            "bNumConfigurations" = 1
            "Bus Power Available" = 250
            "USB Address" = 16
            "Built-In" = No
            "locationID" = 337838080
            "bDeviceSubClass" = 0
            "bcdUSB" = 512
            "USB Product Name" = "Razer Huntsman Mini"
            "PortNum" = 3
            "non-removable" = "no"
            "kUSBSerialNumberString" = "00000000001A"
            "bDeviceProtocol" = 0
            "AppleUSBAlternateServiceRegistryID" = 4298210531
            "IOCFPlugInTypes" = {"9dc7b780-9ec0-11d4-a54f-000a27052861"="IOUSBHostFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
            "IOPowerManagement" = {"DevicePowerState"=0,"CurrentPowerState"=3,"CapabilityFlags"=65536,"MaxPowerState"=4,"DriverPowerState"=3}
            "Device Speed" = 1
            "USB Vendor Name" = "Razer"
            "idVendor" = 5426
            "kUSBCurrentConfiguration" = 1
            "IOGeneralInterest" = "IOCommand is not serializable"
            "kUSBProductString" = "Razer Huntsman Mini"
            "USB Serial Number" = "00000000001A"
            "kUSBVendorString" = "Razer"
            "IOClassNameOverride" = "IOUSBDevice"
          }

Again, I might've done something wrong (I've cp-ed the transaction ID - id 0x100317ce5 - as a case statement in razerkbd_driver).

It detects the keyboard but doesn't change colors. Please advise how I could assist further.

**Comment by ivancernja** [comment]
@sourav-dey Now that I understand it slightly more, I've tried adding cases with both 0x1F and 0x3F but none of them appear to be working. Again, it's possible that I'm doing something wrong so please let me know the steps to take for me to successfully test it.

**Comment by sourav-dey** [comment]
Interesting. So, that means Razer changed the transaction ids for huntsman mini. I guess the only option now is to wait for someone in openrazer repo to implement it and we will do the same in razer-macos.

**Comment by ivancernja** [comment]
@sourav-dey Could be, but again, I'm not much of a coder so I might be doing something wrong.

Best way would be if you could tell me where to put and what to put inside the file - so we can double check.

ie. c/p snippet & line in file

**Comment by ivancernja** [comment]
@sourav-dey Additionally, does it make sense to test all the values, ie. 0x1F, 0x2F, .., 0x9F until the right one?

**Comment by sourav-dey** [comment]
So, what you can do is in function razer_attr_write_mode_wave in razerkbd_driver.c

change to :

1. 
`
ssize_t razer_attr_write_mode_wave(IOUSBDeviceInterface **usb_dev, const char *buf, int count) {
    unsigned char direction = (unsigned char)strtol(buf, NULL, 10);
    struct razer_report report;

    UInt16 product = -1;
    (*usb_dev)->GetDeviceProduct(usb_dev, &product);

    switch(product) {
        case USB_DEVICE_ID_RAZER_ORNATA:
        case USB_DEVICE_ID_RAZER_ORNATA_CHROMA:
        case USB_DEVICE_ID_RAZER_HUNTSMAN_ELITE:
        case USB_DEVICE_ID_RAZER_HUNTSMAN_MINI:
        case USB_DEVICE_ID_RAZER_HUNTSMAN_TE:
        case USB_DEVICE_ID_RAZER_BLACKWIDOW_2019:
        case USB_DEVICE_ID_RAZER_HUNTSMAN:
        case USB_DEVICE_ID_RAZER_BLACKWIDOW_ESSENTIAL:
        case USB_DEVICE_ID_RAZER_CYNOSA_CHROMA:
            report = razer_chroma_extended_matrix_effect_wave(VARSTORE, BACKLIGHT_LED, direction);
            break;

        case USB_DEVICE_ID_RAZER_BLACKWIDOW_CHROMA_V2:
            report = razer_chroma_standard_matrix_effect_wave(VARSTORE, BACKLIGHT_LED, direction);
            report.transaction_id.id = 0x3F;  // TODO move to a usb_device variable
            break;

        case USB_DEVICE_ID_RAZER_TARTARUS_V2:
        case USB_DEVICE_ID_RAZER_BLACKWIDOW_ELITE:
        case USB_DEVICE_ID_RAZER_CYNOSA_V2:
            report = razer_chroma_extended_matrix_effect_wave(VARSTORE, BACKLIGHT_LED, direction);
            report.transaction_id.id = 0x1F;
            break;

        default:
            report = razer_chroma_standard_matrix_effect_wave(VARSTORE, BACKLIGHT_LED, direction);
            break;
    }
    razer_send_payload(usb_dev, &report);

    return count;
}
`


2. Test if wave works.

3. If not:
`
ssize_t razer_attr_write_mode_wave(IOUSBDeviceInterface **usb_dev, const char *buf, int count) {
    unsigned char direction = (unsigned char)strtol(buf, NULL, 10);
    struct razer_report report;

    UInt16 product = -1;
    (*usb_dev)->GetDeviceProduct(usb_dev, &product);

    switch(product) {
        case USB_DEVICE_ID_RAZER_ORNATA:
        case USB_DEVICE_ID_RAZER_ORNATA_CHROMA:
        case USB_DEVICE_ID_RAZER_HUNTSMAN_ELITE:
        case USB_DEVICE_ID_RAZER_HUNTSMAN_TE:
        case USB_DEVICE_ID_RAZER_BLACKWIDOW_2019:
        case USB_DEVICE_ID_RAZER_HUNTSMAN:
        case USB_DEVICE_ID_RAZER_BLACKWIDOW_ESSENTIAL:
        case USB_DEVICE_ID_RAZER_CYNOSA_CHROMA:
            report = razer_chroma_extended_matrix_effect_wave(VARSTORE, BACKLIGHT_LED, direction);
            break;

        case USB_DEVICE_ID_RAZER_BLACKWIDOW_CHROMA_V2:
        case USB_DEVICE_ID_RAZER_HUNTSMAN_MINI:
            report = razer_chroma_standard_matrix_effect_wave(VARSTORE, BACKLIGHT_LED, direction);
            report.transaction_id.id = 0x3F;  // TODO move to a usb_device variable
            break;

        case USB_DEVICE_ID_RAZER_TARTARUS_V2:
        case USB_DEVICE_ID_RAZER_BLACKWIDOW_ELITE:
        case USB_DEVICE_ID_RAZER_CYNOSA_V2:
            report = razer_chroma_extended_matrix_effect_wave(VARSTORE, BACKLIGHT_LED, direction);
            report.transaction_id.id = 0x1F;
            break;

        default:
            report = razer_chroma_standard_matrix_effect_wave(VARSTORE, BACKLIGHT_LED, direction);
            break;
    }
    razer_send_payload(usb_dev, &report);

    return count;
}
`

4. Test again if only wave works
5. If not:
`
ssize_t razer_attr_write_mode_wave(IOUSBDeviceInterface **usb_dev, const char *buf, int count) {
    unsigned char direction = (unsigned char)strtol(buf, NULL, 10);
    struct razer_report report;

    UInt16 product = -1;
    (*usb_dev)->GetDeviceProduct(usb_dev, &product);

    switch(product) {
        case USB_DEVICE_ID_RAZER_ORNATA:
        case USB_DEVICE_ID_RAZER_ORNATA_CHROMA:
        case USB_DEVICE_ID_RAZER_HUNTSMAN_ELITE:
        case USB_DEVICE_ID_RAZER_HUNTSMAN_TE:
        case USB_DEVICE_ID_RAZER_BLACKWIDOW_2019:
        case USB_DEVICE_ID_RAZER_HUNTSMAN:
        case USB_DEVICE_ID_RAZER_BLACKWIDOW_ESSENTIAL:
        case USB_DEVICE_ID_RAZER_CYNOSA_CHROMA:
            report = razer_chroma_extended_matrix_effect_wave(VARSTORE, BACKLIGHT_LED, direction);
            break;

        case USB_DEVICE_ID_RAZER_BLACKWIDOW_CHROMA_V2:
            report = razer_chroma_standard_matrix_effect_wave(VARSTORE, BACKLIGHT_LED, direction);
            report.transaction_id.id = 0x3F;  // TODO move to a usb_device variable
            break;

        case USB_DEVICE_ID_RAZER_TARTARUS_V2:
        case USB_DEVICE_ID_RAZER_BLACKWIDOW_ELITE:
        case USB_DEVICE_ID_RAZER_CYNOSA_V2:
        case USB_DEVICE_ID_RAZER_HUNTSMAN_MINI:
            report = razer_chroma_extended_matrix_effect_wave(VARSTORE, BACKLIGHT_LED, direction);
            report.transaction_id.id = 0x1F;
            break;

        default:
            report = razer_chroma_standard_matrix_effect_wave(VARSTORE, BACKLIGHT_LED, direction);
            break;
    }
    razer_send_payload(usb_dev, &report);

    return count;
}
`

6. Test if wave only works.
7. If not, then change report.transaction_id.id to all values one by one and test i.e., 0x1F, 0x2F, .., 0x9F. Test in between the change.

**Comment by ivancernja** [comment]
Thanks @sourav-dey - I've tried all the numbers up until 30 - none of them seemed to be doing the trick.

What else can we do?

**Comment by darkstriders** [comment]
Please take a look at **[this commit](https://github.com/openrazer/openrazer/pull/1431)** @dhobi

**Comment by dhobi** [comment]
Looks like https://github.com/MasterEnoc/openrazer/commit/a4ced32fb74cd49138f502184643ec1ec18d0de5 has everything we need to know. 👍
