### ISSUE TITLE
App will only recognize 2 devices at a time.

### ISSUE THREAD

**Issue by scorpiontank013** [1kc/razer-macos#119]
I currently have 4 Razer Chroma devices connected to my mac, 3 of which are supported items. I have noticed that this app will only recognize 2 of the 3 supported devices at once. Is this a current limitation of the app, or am I potentially not doing something correctly?

**Comment by sourav-dey** [comment]
What are the devices you have? There is a limitation on the UI if you have multiple of same device type connected, like multiple keyboards, multiple mouse etc.

**Comment by scorpiontank013** [comment]
Ah that is probably it. I have a BlackWidow Elite, goliathus chroma extended, and firefly v2. I can only see one of the mousemats at once. Any plans to update this?

**Comment by xenokira** [comment]
I wonder if this is my issue as well. I have a total of 9 chroma devices, but only ever see 6 in the menu. My devices are listed below. I'm guessing some are considered the same type?

* Core X Chroma
* Huntsman Elite
* Basilisk Ultimate Wireless
* Mouse Charging Dock
* Firefly (mouse pad)
* Nommo Chroma
* Laptop stand Chroma (maybe this one just isn't supported)
* Bungee Chroma / v2
* Base v2

Seems to be the Bungee, Base v2, and Mouse charging dock that rotate for what shows up in the menu.

**Comment by dhobi** [comment]
Yes, razer-macos differs between the following device types (one device is shown at max):
keyboard, mouse, mousedock, mousemat, egpu, headphone and accessory.

Support to show all Razer devices is coming soon™️

**Comment by dhobi** [comment]
Please give the latest version a go (0.3.7+). All razer-macos supported devices should be listed now.
