### ISSUE TITLE
[Feature Request] Option to turnoff light when screen saver is active

### ISSUE THREAD

**Issue by ivanddm** [1kc/razer-macos#122]
Hi there,

First of all, I can't thank you enough for this application, really! 🙏🏻

One thing that I would love to have is the option to turn off the keyboard lights whenever the screensaver is activated or the screen goes to sleep.

Thanks in advance and keep up with the amazing job.

**Comment by gratefulsorceror** [comment]
I second this!! While I absolutely love the program and the life it’s given my keyboard, it’s very bright with the pudding caps I installed on it at night. Especially with the wave setting. A sleep function on screensaver would be much appreciated; and I understand it may be difficult and timely but I imagine none of us are in a rush. Thank you.

**Comment by kmflash** [comment]
Bump!

**Comment by Glaferg** [comment]
Bump. This NEEDS to happen.

**Comment by appleluis** [comment]
Bump! I absolutely love this, I have already set everything in my Setup to turn off at a certain time, this would be AMAZING!!

**Comment by dhobi** [comment]
I guess we could try to implement this with the help of the powerMonitor: https://www.electronjs.org/docs/api/power-monitor

To reenable your devices to the previous state when waking up, I'd suggest to implement #207 first though.
