### ISSUE TITLE
Custom color produces JavaScript error 

### ISSUE THREAD

**Issue by kmflash** [1kc/razer-macos#123]
On Big Sur (11.0.1) I currently get a JS TypeError when selecting any custom color option. 

Additionally, the "Set Custom Color and DPI" option opens a blank window, which I'm guessing is related to the same issue.

<img width="328" alt="Screen Shot 2020-12-07 at 5 16 46 PM" src="https://user-images.githubusercontent.com/21106120/101412247-43555f00-38b0-11eb-9d18-dea45528fb79.png">

<img width="612" alt="Screen Shot 2020-12-07 at 5 19 43 PM" src="https://user-images.githubusercontent.com/21106120/101412379-84e60a00-38b0-11eb-9c34-c136d6692801.png">

**Comment by 1kc** [comment]
For now you can use the previous release. I’ll have a look at it over the weekend.

On 8 Dec 2020, at 8:21 am, kmflash <notifications@github.com> wrote:

﻿

On Big Sur (11.0.1) I currently get a JS TypeError when selecting any custom color option.

Additionally, the "Set Custom Color and DPI" option opens a blank window, which I'm guessing is related to the same issue.

[Screen Shot 2020-12-07 at 5 16 46 PM]<https://user-images.githubusercontent.com/21106120/101412247-43555f00-38b0-11eb-9d18-dea45528fb79.png>

[Screen Shot 2020-12-07 at 5 19 43 PM]<https://user-images.githubusercontent.com/21106120/101412379-84e60a00-38b0-11eb-9c34-c136d6692801.png>

**Comment by ThomObarski** [comment]
+1 Experiencing same issue on Catalina 10.15.7

**Comment by 1kc** [comment]
Fixed in master, will make a new release version soon.
