### ISSUE TITLE
It doesn't change color

### ISSUE THREAD

**Issue by andresmarcelo11** [1kc/razer-macos#127]
Hi! First of all, thanks for creating this. I appreciate it :) I have a Blackwidow Chroma 2019 and I can't change the color of my keyboard, it does detect it, but after I click on any of the options it doesn't work for me :(. I would appreciate a little bit of help :)
![Screenshot 2020-12-08 at 13 54 40](https://user-images.githubusercontent.com/75697370/101534539-ed8ac080-395c-11eb-88b7-3ece1cac01af.png)

**Comment by gratefulsorceror** [comment]
Hey brother, I have the black widow elite and I assume it works the same way, but the keyboards have onboard profiles, typically accessed by holding down the function and option keys on the right side of the keyboard. Change the onboard profile over to white setting typically and it should work

**Comment by andresmarcelo11** [comment]
Thanks bro, it worked!!!!
