### ISSUE TITLE
Nothing shows up on window

### ISSUE THREAD

**Issue by cryptographic1337** [1kc/razer-macos#129]
**OS:** Catalina 10.15.7
**Product:** Any device
**Issue:** When I try to set a custom color on my mousepad or set a custom dpi on my mouse, a window will pop up but it will just be blank. [Photo](https://gyazo.com/e7ad80e10eea8b667f89c2a604819fcf)
**Steps I've tried to troubleshoot:** Restarting Razer MacOS program, restarting computer

**Comment by XyrizJak** [comment]
Same for me. nothing shows up at all in any way.

**Comment by 1kc** [comment]
I'll have a go at fixing this over the weekend, have you tried using older releases for now?

**Comment by XyrizJak** [comment]
I haven’t. This is the first one I try. Do you want me to try older versions?

**Comment by Zinfindel** [comment]
I also have this issue

**Comment by 1kc** [comment]
should be fixed now
