### ISSUE TITLE
Added ability to choose from not only a slider in custom slider, but also hex?

### ISSUE THREAD

**Issue by ZappoKiller** [1kc/razer-macos#14]

**Comment by alexfry** [comment]
Should there not also be a saturation slider? Rather than just Hue?

**Comment by 1kc** [comment]
This library is what is currently being used: https://casesandberg.github.io/react-color/

This one looks appropriate. I will also try to add the hex.
![Screen Shot 2020-06-04 at 11 13 31 am](https://user-images.githubusercontent.com/20840688/83704067-6e869980-a654-11ea-9cf1-0962566ad6b5.png)

**Comment by 1kc** [comment]
This has been added in the latest version :)
