### ISSUE TITLE
100% brightness on App does not actually go to 100% brightness on keyboard

### ISSUE THREAD

**Issue by ozziekhoo** [1kc/razer-macos#142]
Great work @1kc @davidcui2 and everyone else on the new release. I am running into this slight issue with this brightness setting where it the percentage doesn't accurately reflect the actual brightness of the peripheral?

For example on my Blackwidow 2019, on the keyboard there are 20 steps of brightness as per the keyboard controls (fn + f11/f12). However, when I use the slider on the app, 100% only goes to the 14th step of brightness.

Not sure if this is just with this keyboard model or other devices as well, so if someone else could test on a different model they are having that would be great. 

Maybe it is an issue with my OS as I am running MacOS 10.14, however all other features work as expected.

**Comment by gratefulsorceror** [comment]
i too can confirm this issue on 10.15.7. The brightness is 6 steps below max brightness.

**Comment by dhobi** [comment]
I experience the same issue with a Razer Cynosa V2
