### ISSUE TITLE
Hi. noob here...couple questions

### ISSUE THREAD

**Issue by smithbrendan57** [1kc/razer-macos#148]
Sorry if this sounds dumb, i barely have any idea what im doing.

-Got my basilik mouse and goliath pad to sync, working perfectly, thank you!
-any plans to add blackwidow v3 pro keyboard?
-not sure what i did wrong but i cant get the chroma headstand to connect 

btw this is the greatest thing ive ever seen developed. F*** razer for not making mac os compatible

**Comment by dhobi** [comment]
Progress for BlackWidow V3 Pro will be tracked here #151

If your headstand is still not supported with the latest version 0.3.7 and there is currently no open issue for it, create a new one please. 👍
