### ISSUE TITLE
Razer Basilisk V2 supported since 0.3.1 but not working

### ISSUE THREAD

**Issue by StevenBoelhouwer** [1kc/razer-macos#149]
Seen a pull request for the Razer Basilisk V2 and is merged in master but the Razer Basilisk V2 is never found for me.
What kind of information do you need to troubleshoot/debug? And how can I help? :)

**Comment by dhobi** [comment]
It's confirmed working here: #87
Please follow the instructions / troubleshooting in there. If it's still not working for you, add a comment in #87
