### ISSUE TITLE
Instructions for uninstallation/uninstaller

### ISSUE THREAD

**Issue by push7joshi** [1kc/razer-macos#15]
Thank you for your effort. It works great with the keyboard (Blackwidow Elite)

I have a Deathadder Elite mouse as well that does not sync up with the colors as I installed the manager, which I understand might be supported later. While uninstalling using appcleaner it seems the effects still persist. Would you advise on how I could safely uninstall this?
Thanks!

ps: I would be happy to contribute to gear testing efforts if required (saw your comment on reddit 3 days ago about mouse development)

**Comment by 1kc** [comment]
Hi,
Thanks for wanting to help out, that's great!
The colour effects are hardware based, same as openrazer on Linux on which this project is based. 
This means to remove the effects, you will either need to reinstall the app and pick one that you will be sticking stick with, or use Synapse on Windows to reset the keyboard back to its original setting.
Cheers

**Comment by push7joshi** [comment]
Thanks! I will try that out.

**Comment by 1kc** [comment]
Could you please help me test the new mouse effects? I can confirm that the animations are working, just not changing colours. Thanks!

See https://github.com/1kc/razer-macos/releases

**Comment by push7joshi** [comment]
Sure, will update you in a couple hours.

**Comment by push7joshi** [comment]
I installed the manager from the link above, it identifies my Deathadder Elite, however the effects do not come up on the mouse.
I tried a refresh, unplug and refresh again to troubleshoot. If there's anything specific you would like me to try, let me know.
Please see the picture and screenshot attached. I was trying to set the logo to white.
![IMG_8733](https://user-images.githubusercontent.com/1506622/83909009-9eee3680-a72d-11ea-9cac-97ad96aa4c3b.jpg)
![effects-manager](https://user-images.githubusercontent.com/1506622/83909079-baf1d800-a72d-11ea-8342-2b888da4809b.png)

**Comment by alexfry** [comment]
Same deal here.

The mouse is recognised correctly, but the settings have no effect.

I think I've seen you mention elsewhere that you're setting on board profiles?
As I understand it most of their mice (Lancehead for sure) do no store lighting settings in their on device profiles, and need an active connection to Synapse 3. Is there a different protocol for sending lighting effects in that scenario?

![Screen Shot 2020-06-06 at 8 46 00 am](https://user-images.githubusercontent.com/900885/83928294-96037080-a7d2-11ea-9075-1ea9700c8a1f.png)

**Comment by 1kc** [comment]
Thanks for the testing efforts guys. It seems like my older mouse (DeathAdder 2013) operates differently to yours. I have made some changes so that it should work on the new DeathAdder and the Wireless Lancehead on v0.1.5.
If this change works for you guys, I will add the rest of the effects.

https://github.com/1kc/razer-macos/releases

I believe most effect are working properly in openrazer without Synapse 3, though an active connection is required for complex effects. Openrazer is pretty much a reversed engineered Synapse 3.

**Comment by alexfry** [comment]
That's more like it!
Nice work!!

![2898AC64-263B-423B-89A9-ACA3B9468202_1_105_c](https://user-images.githubusercontent.com/900885/83935330-0b376b80-a7fc-11ea-8e17-d2cec24d56c0.jpeg)

**Comment by 1kc** [comment]
Awesome! Will add the rest of the mouse effects soon.

**Comment by push7joshi** [comment]
Yup, can confirm, it works for me too. Thanks!

**Comment by alexfry** [comment]
Some interesting things I noticed.

Whatever method you're using to set the colour on my Lancehead's logo is actually surviving the mouse being turned on an off, which according to Razer's support people isn't actually possible. (Clearly not true)

Also, when I bootcamp across to Windows and let Synapse 3 take over again, whilst Synapse is talking to the mouse it acts as before, but when it disconnects, the colour set by Razer-macos is applied to both the logo and the side and scroll LEDs.

Agains, surviving a full reboot back into MacOS

Very interesting.

**Comment by 1kc** [comment]
That's an interesting observation. I can confirm that Razer-macos and openrazer both set permanent hardware-based effects. But when I plug it back into a Windows computer with Synapse 3, everything resets.

Since I don't own a new mouse, I might need your help again once I start work on the other effects.
