### ISSUE TITLE
Can we get an "About Razer-macos"?

### ISSUE THREAD

**Issue by razosx12** [1kc/razer-macos#150]
Not sure where to place a feature request, but it would be nice to have an "About Razer-macos" or Help that links back to the github page to check for updates, and also show the current version installed (based on what was packaged in the build).

**Comment by ozziekhoo** [comment]
Not sure if you know this but you could always go to Finder > Applications > right-click Razer-MacOS > Get Info to find the current version

**Comment by 1kc** [comment]
@razosx12 Very good idea cheers, will try to add this in next version

**Comment by 1kc** [comment]
Done!
