### ISSUE TITLE
Wave speed doesn't work

### ISSUE THREAD

**Issue by Stanman04** [1kc/razer-macos#160]
When I change the wave speed, it doesn't work, also, please add the ripple effect.

Except for that, amazing work! I really appreciate it!

**Comment by akaler** [comment]
@Stanman04 what keyboard are you using?

**Comment by Stanman04** [comment]
I am using the Razer Ornata v2

**Comment by akaler** [comment]
That's weird, it should work on ornata v2. Could you answer these questions:
does the keyboard go in wave mode at all? 
if so, what speed does it run at? 
Did the wave mode work in the previous versions?

**Comment by Stanman04** [comment]
it does go into wave mode, its just that the speed doesn't change
the speed is constant at normal, and when I change the speed, the wave just tarts over, at the same speed. no difference between ultra slow and lightning speed
the wave worked since v3.2 which is when I first downloaded it, still works, just the speed can't be changed

**Comment by dhobi** [comment]
I'll change the issue title since ripple effect is available in the meantime.

**Comment by james-pound** [comment]
Same issue here, with the speed setting for wave effect: 
BlackWidow V3 TKL
App version 0.4.8

Could you also add a 0 speed option to the wave effect? Like having a multi colour static effect. 

Great work and many thanks!
