### ISSUE TITLE
Menu bar icon is black in Big Sur

### ISSUE THREAD

**Issue by aheze** [1kc/razer-macos#164]
All the menu bar icons are white, except for this app...

<img width="1440" alt="Screen Shot 2020-12-29 at 8 25 07 PM" src="https://user-images.githubusercontent.com/49819455/103329940-05ada700-4a14-11eb-8a83-764310b365a4.png">

It's white in dark mode, but it should be white in light mode too on Big Sur. This doesn't affect anything at all, but it just kind of looks out of place.

**Comment by 1kc** [comment]
It should detect light or dark mode automatically. Does restarting it help at all? If not something is broken.

On 30 Dec 2020, at 2:27 pm, Zheng <notifications@github.com> wrote:

﻿

All the menu bar icons are white, except for this app...

[Screen Shot 2020-12-29 at 8 25 07 PM]<https://user-images.githubusercontent.com/49819455/103329940-05ada700-4a14-11eb-8a83-764310b365a4.png>

Dark mode works fine, but the icons should be white in light mode too. This doesn't affect anything at all, but it just kind of looks out of place.

**Comment by aheze** [comment]
@1kc Ah I actually meant that it should be white regardless of dark mode or not.

Screenshots
| --- |
**Light Mode**
![](https://user-images.githubusercontent.com/49819455/103335576-28e35100-4a2a-11eb-9929-170dce3b6f94.png)
**Dark Mode**
![](https://user-images.githubusercontent.com/49819455/103335578-2aad1480-4a2a-11eb-8b7c-20fdc1ba342c.png)

It's detecting the dark mode change automatically, but it should be always white (I think it's a new design guideline for Big Sur)

**Comment by 1kc** [comment]
Oh I see. Will change it in the next release.


On 30 Dec 2020, at 5:07 pm, Zheng <notifications@github.com> wrote:

﻿

@1kc<https://github.com/1kc> Ah I actually meant that it should be white regardless of dark mode or not.

Screenshots
Light Mode
[https://user-images.githubusercontent.com/49819455/103335576-28e35100-4a2a-11eb-9929-170dce3b6f94.png]<https://user-images.githubusercontent.com/49819455/103335576-28e35100-4a2a-11eb-9929-170dce3b6f94.png>
Dark Mode
[https://user-images.githubusercontent.com/49819455/103335578-2aad1480-4a2a-11eb-8b7c-20fdc1ba342c.png]<https://user-images.githubusercontent.com/49819455/103335578-2aad1480-4a2a-11eb-8b7c-20fdc1ba342c.png>

It's detecting the dark mode change automatically, but it should be always white (I think it's a new design guideline for Big Sur)
