### ISSUE TITLE
{REQUEST} Razer Chroma Custom Profiles

### ISSUE THREAD

**Issue by Zfauser** [1kc/razer-macos#169]
Is there anyway to add support for pre-configured razer chroma profiles that you had already configured in windows?

**Comment by 1kc** [comment]
This will be amazing but it is super challening to implement. I reckon we would require a whole team of people working on it.

**Comment by Zfauser** [comment]
Yes I could see why. Maybe it could be done in the future

**Comment by Zfauser** [comment]
By the way great work on this
