### ISSUE TITLE
Colour change works on Orbweaver but should this software also control the key presses?

### ISSUE THREAD

**Issue by RoscoPeeko** [1kc/razer-macos#170]
Thankyou so much for making this software. I use an orbweaver to control my ProTools system and am in a real bind.
I came across this the other day while desperately searching for a solution.

I am using vers 0.3.3 on mac OS10.12.6 (Sierra)
The orbweaver shows up in the software, but is greyed out. This does not change when I refresh the device list.

I can get the colour changes to work on my Orbweaver, but is this software suppose to be able to control the key presses as well?

**Comment by 1kc** [comment]
No this does not control the key presses. Maybe this is what you are looking for? https://karabiner-elements.pqrs.org/
