### ISSUE TITLE
When is v3.4.0 coming out?

### ISSUE THREAD

**Issue by Stanman04** [1kc/razer-macos#171]
just a question, because I am so excited for the improved wave speed and two color starlight.
🙂

**Comment by 1kc** [comment]
Will see if I have some time today to merge the changes

On 5 Jan 2021, at 4:10 am, Stanman04 <notifications@github.com> wrote:

﻿

just a question, because I am so excited for the improved wave speed and two color starlight.
🙂

**Comment by Stanman04** [comment]
Ok, thank you very much, both for that,  and for this program in general.
: )

**Comment by 1kc** [comment]
its out now!
