### ISSUE TITLE
Not recognizing Razer Huntsman Mini 60% Keyboard with red switches

### ISSUE THREAD

**Issue by prodbycrazi** [1kc/razer-macos#173]
I am on macOS Big Sur Version 11.1 and have tested multiple usb ports to make sure that wasn't the issue, it didn't pop up as a device. However my basilisk ultimate works perfectly with it.

**Comment by Stanman04** [comment]
did you try and refresh?

**Comment by sourav-dey** [comment]
@prodbycrazi Apparently the signal value for huntsman mini is different from general razer devices from our previous testing. So we need to wait until the upstream openrazer implements it for linux.

**Comment by dhobi** [comment]
Huntsman Mini progress is tracked in #107.
