### ISSUE TITLE
Razer Basilisk V2 not recognized

### ISSUE THREAD

**Issue by jnchng** [1kc/razer-macos#175]
Hey there, I downloaded 0.3.3 yesterday and it didn't recognize my Basilisk V2 mouse. There's no message saying "no device found" either; just the color/cycle selection. I downloaded 0.3.4 and tried again just now, but it's not showing up on there either. I'm on Big Sur 11.1. The mouse is connected via USB to USB-C adapter and working on my laptop, so I'm not sure why it's not being recognized.

Let me know if I can provide any more info. Thanks, you guys are doing awesome work!

**Comment by xDedication7x** [comment]
I have the same problem on Big Sur 11.1 and Catalina 10.15.7.

**Comment by Oshawott12** [comment]
Same problem with Catalina 10.15.3, on 0.3.4.

**Comment by StevenBoelhouwer** [comment]
Same, see #149

**Comment by dhobi** [comment]
It's confirmed to be working here: #87
Please follow the instructions / troubleshooting in there. If it's still not working for you, add a comment in #87
