### ISSUE TITLE
Catalina Showing Darkmode Taskbar Icon no matter what

### ISSUE THREAD

**Issue by minimurti** [1kc/razer-macos#176]
When switching between light and dark mode in 10.15.7, the icon on the top taskbar insists on showing the "icon-darkmode.png" image no matter what. (if you change the filename it will show that icon)

**Comment by 1kc** [comment]
That was an intentional change since someone raised that in Big Sur the icon colour is always dark. I guess we’d have to detect what macos version it is


On 7 Jan 2021, at 5:54 am, minimurti <notifications@github.com> wrote:

﻿

When switching between light and dark mode in 10.15.7, the icon on the top taskbar insists on showing the "icon-darkmode.png" image no matter what. (if you change the filename it will show that icon)

**Comment by MNUser** [comment]
According to [this stackoverflow thread](https://stackoverflow.com/questions/41664208/electron-tray-icon-change-depending-on-dark-theme) MacOS can set the color automatically, depending on usage of a light or dark wallpaper and not only based on dark mode enabled or disabled.

I created a [pull request](https://github.com/1kc/razer-macos/pull/178) with the necessary changes

menubar icon - dark wallpaper - darkmode disabled:
<img width="595" alt="menubar icon - dark wallpaper - darkmode disabled" src="https://user-images.githubusercontent.com/25120740/103832356-65dcc280-507e-11eb-8acb-9d0894101447.png">

menubar icon - dark wallpaper - darkmode enabled:
<img width="595" alt="menubar icon - dark wallpaper - darkmode enabled" src="https://user-images.githubusercontent.com/25120740/103832399-7db44680-507e-11eb-92ac-35794773b55b.png">

menubar icon - light wallpaper - darkmode disabled:
<img width="595" alt="menubar icon - light wallpaper - darkmode enabled" src="https://user-images.githubusercontent.com/25120740/103832461-9f153280-507e-11eb-8ae2-67bcdd10a1bc.png">

menubar icon - light wallpaper - darkmode disabled:
<img width="595" alt="menubar icon - light wallpaper - darkmode disabled" src="https://user-images.githubusercontent.com/25120740/103832440-8efd5300-507e-11eb-8b75-8d2186a2af2f.png">

**Comment by dhobi** [comment]
This should be fixed in the meantime.
