### ISSUE TITLE
Razer Naga Support

### ISSUE THREAD

**Issue by minimurti** [1kc/razer-macos#177]
Hello I love the app and I use it for my Ornata Chroma. Would it be possible to also support the naga mouse? Thank you :)

**Comment by LJ-03** [comment]
I'd like to second this. Razer Naga Pro isn't showing up.

**Comment by Trojaan2112** [comment]
Yes, I second or third this. Great software, but Razer Naga Pro isn't supported. If possible please make this compatible. Thanks, keep up the great work.

**Comment by Suma-xy** [comment]
@minimurti Razer Naga support is available since v0.3.5. You can close the issue.

**Comment by Trojaan2112** [comment]
I meant the razer naga pro wireless.

**Comment by dhobi** [comment]
Closed in favor of #219 (more specific title)
