### ISSUE TITLE
Razer nommo chroma

### ISSUE THREAD

**Issue by gogmang0923** [1kc/razer-macos#181]
Can you support the Razer nommo chroma? I want to control my speakers RGB at Mac. Please help me.

**Comment by joshtbernstein** [comment]
I've opened an issue (https://github.com/1kc/razer-macos/issues/58) for this already. Maybe close this out and follow that one?

**Comment by gogmang0923** [comment]
Ok. Thanks

**Comment by joshtbernstein** [comment]
@gogmang0923 This was added in v0.3.6.

**Comment by billstevenson** [comment]
Commenting here since https://github.com/1kc/razer-macos/issues/58 is closed - I am on 0.3.6 and cannot see my Nommo Chroma speakers. I suspect that will be fixed by https://github.com/1kc/razer-macos/pull/256 when a release containing it is pushed.

**Comment by 1kc** [comment]
Try downloading the latest dmg file

**Comment by billstevenson** [comment]
Ok, I verified that I can see them. It's an accessory class competition issue. The speakers, the headphone stand, and the mouse bungee all appear to be competing, and only one can be configured at a time.

Is there a bug tracking being able to talk to multiple devices of the same accessory class? Curious about if there's a technical barrier (e.g., upstream in openrazer) or if if there's just a need to refactor some UI code in the Mac app (e.g., to use submenus for "Mice", "Keyboards", "Speakers", etc. and enumerate all devices within them, etc.  (I would think that there would be a cheaper iteration where you just have to scroll the one menu for a really long time if you have a lot of devices...)

**Comment by dhobi** [comment]
Please create an issue (if it does not already exist):
Support/Show multiple devices of same device type 👍

**Comment by dhobi** [comment]
Should be possible with the latest version 0.3.7 now.

**Comment by billstevenson** [comment]
Verified, looks good, thanks for landing it.

**Comment by dhobi** [comment]
I'll close the issue now. Please reopen if Razer Nommo Chroma is not working for you.
