### ISSUE TITLE
Not as much of an issue as just a request

### ISSUE THREAD

**Issue by Stanman04** [1kc/razer-macos#183]
Hello,
I am Stan, and I would really love to learn to code. I would really want to start off with creating a program for Mac which would set a specific key to have a specific color, and have the ability to be turned off. I am a complete newbie, and do not know anything. Seeing as here are many talented individuals, I wish that one of you could help me with that. 
I need someone to tell me what program would have to be used to do this, how to assign a specific color to a specific key, and allow for it to be turned off (aka the none/off function).

If anyone could help I would be extremely grateful.
if you would like, you could just respond to this, or email me at stanislawisspitfire@gmail.com

I have a Razer Ornata v2 and would love for the program to run on that.
Thank you in advance!! 🙂

**Comment by 1kc** [comment]
Hi Stan,

I would suggest starting programming tutorials first. As jumping immediately into a project can be a bit overwhelming starting from an absolute beginner.
This project involves front end JavaScript with react as well as C which is a low level language. Only when you understand the code base you can start contributing and this can take a bit of time.

I have found front end development to be quite easy to grasp as a beginner as it’s very visual. One course I have done in the past was free code camp.

Hope this helps and I’m glad this has inspired you to look into learning how to program

On 9 Jan 2021, at 8:11 am, Stanman04 <notifications@github.com> wrote:

﻿

Hello,
I am Stan, and I would really love to learn to code. I would really want to start off with creating a program for Mac which would set a specific key to have a specific color, and have the ability to be turned off. I am a complete newbie, and do not know anything. Seeing as here are many talented individuals, I wish that one of you could help me with that.
I need someone to tell me what program would have to be used to do this, how to assign a specific color to a specific key, and allow for it to be turned off (aka the none/off function).

If anyone could help I would be extremely grateful.
if you would like, you could just respond to this, or email me at stanislawisspitfire@gmail.com<mailto:stanislawisspitfire@gmail.com>

I have a Razer Ornata v2 and would love for the program to run on that.
Thank you in advance!! 🙂
