### ISSUE TITLE
Doesn't work after standby

### ISSUE THREAD

**Issue by OliverUrbann** [1kc/razer-macos#19]
After program start the app works as expected. After a standby of macOS the app is still running and ich can click everything, but the color change is not applied anymore. After restarting the app it works again.

Tried on a MacBook Po 16, macOS Cataline and Razer Ornata Chroma.

**Comment by 1kc** [comment]
Does the colour effect stay when you exit the app? It should since the settings are stored on the keyboard's hardware. I use the MacBook Pro 16 with the Razer Huntsman.

**Comment by OliverUrbann** [comment]
Yes, it stays after quitting, no matter if the app is still working or not (after standby). It also stays after power safe etc. when app is not active.

**Comment by 1kc** [comment]
Yes, this is the expected behaviour. Please see #15. With regards to standby, are you saying that the app does not function after waking up from sleep. If so I will look into it. Cheers.

**Comment by 1kc** [comment]
Please give it another go with the latest release. Custom colour settings now persist after restarting the app.
