### ISSUE TITLE
PLS MAKE WORK FOR RAZER BASILISK V2 @~@

### ISSUE THREAD

**Issue by Swagger10112** [1kc/razer-macos#196]
PRETTY PLS MAK EWORKD when i press the boxy thingys only two things show up.
![Screen Shot 2021-01-15 at 1 25 17 PM](https://user-images.githubusercontent.com/77509450/104769569-1d37a000-5735-11eb-8c68-79c2da63fedf.png)

**Comment by Identidy** [comment]
THE SAME THING HAPPENS TO ME I'VE GOT THE RAZER BLACKWIDOW AND DEATHADDER ELITE AND ITS SO ANNOYING

**Comment by 1kc** [comment]
Doesn't seem to be supported here: https://github.com/openrazer/openrazer/issues/1078
Not much we can do right now 😞

**Comment by 1kc** [comment]
please give the new version a go, seems fixed?

**Comment by dhobi** [comment]
It's confirmed to be working here: #87
Please follow the instructions / troubleshooting in there. If it's still not working for you, add a comment in #87
