### ISSUE TITLE
Razer Abyssus V2 color scheme

### ISSUE THREAD

**Issue by storkinsj** [1kc/razer-macos#208]
Thanks for adding this device.
The Razer Abyssus V2 has a limited color scheme which includes light blue dark blue and green. The menus show white and red as possibilities but these are not available.

In addition, the newer effects listed do not work. While there is a menu for older effects, it is not clear that the new ones won't work.  As it is possible to alter the menu based on what is connected (or else we wouldn't see the Abyssus V2 menu), the menu should reflect the capabilities of that device.

In addition there does not seem to be any reaction to the brightness control. There isn't really a brightness control per se, but the brightness for the keyboard seems to work from the "keyboard custom settings" lever. That is awkward too, since that control is supposed to be for setting custom colors.

Version: 0.3.4
Keyboard: Razer Blackwidow Chroma
Mouse: Razer Abyssus V2
OS: Catalina 10.15.7

**Comment by dhobi** [comment]
There is currently no mechanism to return a list of capabilities for a detected device in razer-macos. 

A menu entry does render based on the detected device type such as Mouse, Keyboard, Headset, Mousemat, ... which means that the menu entry will always contain the maximum amount of capabilities of this type to not limit other devices of the same type. 

A refactoring from type to capabilities detection would be a lot of (testing) work imho.

**Comment by storkinsj** [comment]
Thanks- 
    I was thinking about this one this morning. It is something that exists in synapse of course but it would be tricky to do, although we could group source the matrix by putting out a call to do so or something. It seems potentially more challenging than necessary.
    
       Is there some way we can present device IDs to Synapse to see what it presents, and subsequently catalogue the results?  Great work so far- it is REALLY hard to do this without all the hardware. If you want hardware to test with maybe we can figure out how to make that happen.

**Comment by dhobi** [comment]
Thanks to the openrazer project, razer-macos has already a good indicator on what is possible with which device. It's more about testing with real hardware. I think I've already said the "it should work™, well, theoretically" too many times in my life already and I'm still young... 😃

**Comment by dhobi** [comment]
Since 0.3.7 there is the possibility to give more specific features / missing features / featureConfigurations for a device. I did this for Razer Abyssus V2 (as I own this one):
- Only older model features are shown in the menu
- No red color option

Please reopen (or create a new isssue) if you think this could be further improved.
