### ISSUE TITLE
blackwidow v3 pro please :)

### ISSUE THREAD

**Issue by smithbrendan57** [1kc/razer-macos#213]
this project kicks ass, the only thing its missing is customization for rgb on the blackwidow... i cannot figure it out for the life of me

**Comment by sdanaher** [comment]
Can you boot and enter your password correctly with this keyboard plugged in for MacOS?  I cannot - how did you resolve this?

**Comment by aboedo** [comment]
still no luck with blackwidow v3 pro on 0.3.6. It doesn't show up on the device list with any connection mode. I tried wired, dongle and bluetooth.

**Comment by 1kc** [comment]
The new one added is actually Razer BlackWidow V3, not the Pro one. I'll see if I have some time to add it myself in the future.

**Comment by aboedo** [comment]
Thanks for the quick reply! Happy to test it again and report once it gets added.

**Comment by dhobi** [comment]
Progress for BlackWidow V3 Pro will be tracked here #151
