### ISSUE TITLE
It won't work for my Razer BlackWidow V3 TKL keyboard

### ISSUE THREAD

**Issue by ConstantinosSdfs** [1kc/razer-macos#217]
Hello, I have tried using Razer MacOS but it will not change any of the colors on my keyboard, can you please fix this?

**Comment by missbeckalina** [comment]
I would like to second this request!

**Comment by nielsth** [comment]
I would love to see support for this keyboard as well

**Comment by syaifulsz** [comment]
+1 for this request! Thank you!

**Comment by diogo-redstage** [comment]
I would also add a request for this, I have the Razer BlackWidow V3 TK and would love to see this app supporting this model!
