### ISSUE TITLE
Doesn't work for Razer Basilisk V2 :( (pls fix it)

### ISSUE THREAD

**Issue by Filthic** [1kc/razer-macos#221]
<img width="191" alt="Screen Shot 2021-01-30 at 17 51 05" src="https://user-images.githubusercontent.com/78269173/106360944-e318f180-6323-11eb-9a8b-e51765ebf31e.png">

**Comment by Boselko** [comment]
same with razer huntsman mini

**Comment by joerg-wille** [comment]
Basilisk V2 is not working for me either.
The Basilisk V2 support was added by [sourav-dey](https://github.com/sourav-dey).
The code look ok at first sight, I will ask sourav-dev what the status is for this device.

**Comment by joerg-wille** [comment]
This issue is relates to [issue 87](https://github.com/1kc/razer-macos/issues/87).

**Comment by joeyiscool12** [comment]
Same, my viper ultimate doesnt work either.
