### ISSUE TITLE
Task/Tray Bar Icon Not Showing Up 

### ISSUE THREAD

**Issue by andrewshields933** [1kc/razer-macos#232]
<img width="656" alt="Screen Shot 2021-02-07 at 11 05 25 AM" src="https://user-images.githubusercontent.com/78701132/107156631-65ad3c80-6934-11eb-9630-b12f13a4e7e6.png">

I have restarted computer, and while the app itself does work and controls my keyboard brightness, I can't do anything else because I don't see the icon in the tray bar. How do I get it to appear? I am on Catalina 10.15.1

**Comment by 1kc** [comment]
You have to relaunch it. It doesn’t start but itself at this time
