### ISSUE TITLE
Adding Support For Razer Naga Trinity

### ISSUE THREAD

**Issue by konradgthecoder** [1kc/razer-macos#236]
Hi, I noticed the Razer Naga Trinity is supported by Openrazer, but was not able to modify settings using razer-macos.
I would love to see this mouse supported by the software, are there any plans to do so?
I am a senior computer science student and would be willing to help to make this work! Please let me know what the plans are. Thanks!

**Comment by Tirami26** [comment]
Hey there is already an Issue open with the Razer Naga Trinity (and even a link with an already working app with support) WIP tho. https://github.com/1kc/razer-macos/issues/189

**Comment by dhobi** [comment]
Closed in favor of #189
