### ISSUE TITLE
Razer Huntsman Mini Support support please!

### ISSUE THREAD

**Issue by datguyaiden** [1kc/razer-macos#237]
Could you please add support for the Razer Huntsman Mini? Thanks heaps man!

**Comment by 1kc** [comment]
Huntsman mini is one of those keyboards that hasn't had support yet for a long time. Super unlucky.
See https://github.com/openrazer/openrazer/issues/1230

**Comment by code-path** [comment]
@1kc Please check [this commit](https://github.com/openrazer/openrazer/pull/1431/commits/1bb04d4e8f41dd489c1d2ef969788f35d2606c75), see if you can add Huntsman mini support.

Appreciated.
