### ISSUE TITLE
macOS 10.15.7 and 0.3.6 on Huntsman: icon on menu bar is invisible

### ISSUE THREAD

**Issue by e40** [1kc/razer-macos#239]
I see no icon to the right of the Apple menu, as the `README.md` shows.

In the main window, changing the brightness works.  Changing the color does not.

It was the same on 0.3.4 (when I discovered this excellent project).

Ideas?  Thanks.

**Comment by e40** [comment]
Wow, turns out the icon is invisible.  I clicked next to the leftmost icon and up popped the menu!

**Comment by e40** [comment]
![Screen Shot 2021-02-10 at 9 27 36 AM](https://user-images.githubusercontent.com/89416/107547440-4e638e80-6b82-11eb-9305-a41b8cc1df5d.png)

![Screen Shot 2021-02-10 at 9 27 46 AM](https://user-images.githubusercontent.com/89416/107547459-53c0d900-6b82-11eb-8d09-79faa2760a96.png)

**Comment by e40** [comment]
Same with 0.3.6.  Icon is invisible.

**Comment by 1kc** [comment]
This is because on the new macOs the icons are always light coloured as the menu bar is always dark. Yes this needs to be fixed.

**Comment by e40** [comment]
This is fixed with the latest!  Thanks!
