### ISSUE TITLE
Please add support of razer blackwidow v3 tenkeyless 🙏🏻

### ISSUE THREAD

**Issue by kushney** [1kc/razer-macos#249]
razer blackwidow v3 tenkeyless is not supported currently

**Comment by BenJaine** [comment]
ive been waiting for ages bro, they aint guna add it i have lost hope tbh

**Comment by dhobi** [comment]
Since razer-macos ports the functionality (mainly) from the openrazer project, it would make sense to wait for them to add support for BlackWidow V3 Tenkeyless first.
The current state is here: https://github.com/openrazer/openrazer/issues/1318

**Comment by dhobi** [comment]
For state updates on BlackWidow V3 Tenkeyless: #276
