### ISSUE TITLE
Newest version v0.3.6 is not compatible with macOS < 11

### ISSUE THREAD

**Issue by dhobi** [1kc/razer-macos#251]
https://github.com/1kc/razer-macos/releases/tag/v0.3.6

Starting the application ends in a message like: 
You have macOS 10.13.6 installed. The program requires macOS 11.0 or newer.

**Comment by 1kc** [comment]
thanks for letting me know, trying to fix this now

**Comment by mitsh** [comment]
I've macos 11.2.1 (20D74). It doesn't work.

**Comment by 1kc** [comment]
Please delete the old one and download the new one again: 
There was a problem building for M1/ARM for some reason.

**Comment by mitsh** [comment]
it worked now. thanks!

**Comment by dhobi** [comment]
Can confirm it works for 10.13.6 again!
