### ISSUE TITLE
v0.3.6 doesn't support razer nommo pro.

### ISSUE THREAD

**Issue by sourav-dey** [1kc/razer-macos#253]
v0.3.6 doesn't support/detect razer nommo pro.

**Comment by dhobi** [comment]
Sorry, I've just seen that I forgot to add all the accessory id's to the is_accessory() in razerdevice.c - except of course - the one device I have myself.
I will try to fix this asap. You would need to help me out testing though 😃

**Comment by 1kc** [comment]
Legend! Awesome

**Comment by sourav-dey** [comment]
@dhobi yes sure.. Definitely.

**Comment by 1kc** [comment]
@sourav-dey I have uploaded a new binary

**Comment by sourav-dey** [comment]
@dhobi @1kc It works for nommo-pro. Thanks a lot!
