### ISSUE TITLE
Huntsman mini

### ISSUE THREAD

**Issue by Boselko** [1kc/razer-macos#254]
pls finally support razer huntsman mini

**Comment by dhobi** [comment]
Huntsman Mini progress is tracked in #107. Please do not open multiple issues for the same request.

**Comment by Boselko** [comment]
Sorry for that but the last response was 3.December. Is there any chance u can finish it? I hope, cuz iam waiting like 4 months for this 🙈

S pozdravom Bošeľa 
Pekný zvyšok dňa prajem .
