### ISSUE TITLE
Settings is not stored in the app

### ISSUE THREAD

**Issue by vmuzikar** [1kc/razer-macos#258]
Steps to reproduce:
1. On macOS, set some non-default RGB setting (i.e. different from the spectrum). The settings is store in the device on-board memory, which is fine.
2. Switch to Windows with Synapse installed. This will erase the on-board memory resetting it to default (spectrum).
3. Switch back to macOS. The settings previously set in Step 1 is not applied even if the app is re-launched.

Environment:
* Razer macOS v0.3.6
* macOS 11.2.1
* Razer BlackWidow V3

Would it be possible to store the settings in the app so that it is applied at least at the app launch?
Or, alternatively, provide a CLI interface to launch the app with specified settings?

This is probably related to #234.

**Comment by dhobi** [comment]
I see this and #234 as possible duplicates of #207. Let's track the progress there.
