### ISSUE TITLE
still not working for blackwidow v3 tkl

### ISSUE THREAD

**Issue by BenJaine** [1kc/razer-macos#259]
after reading the patch notes my keyboard still doesnt get detected

**Comment by dhobi** [comment]
Duplicate of #249, #88
The keyboard added in v.0.3.6 is BlackWidow V3 (ProductId: 0x024e) while you want support for BlackWidow V3 Tenkeyless (ProductId: 0x0a24).

**Comment by Bryghton42** [comment]
> after reading the patch notes my keyboard still doesnt get detected

Try changing the on board profiles and then changing the colors.

**Comment by dhobi** [comment]
For state updates on BlackWidow V3 Tenkeyless: #276
