### ISSUE TITLE
Adding, Setting, Saving, & Selecting Custom Color Does not Work on v0.3.6

### ISSUE THREAD

**Issue by WrathofthePast** [1kc/razer-macos#260]
- Save a Custom Color does not work at all
- Selecting a custom color does not work at all
- In the Set a Custom Color window, the secondary custom color tab is unresponsive to selection
- Set a Custom Color window will only appear if attempting to select a custom color for all devices
- Add Custom Color to individual Devices does nothing
- Add Custom Color for all devices adds a color to the list, but does not bring up the Set a Custom Color Window unless attempting to select

Note: This issue has been happening on multi versions: v0.3.2, v0.3.5, & v0.3.6 -possibly more, but these are all that I have checked. All other lightning functions work.
Razer Equipment:

- Deathadder Elite (had for all 3 versions this was happening on)
- Core X Chroma (had for all 3 versions this was happening on)
- Huntsman v2 Analog (issue was happening before I received it today, so its support not being added yet is not a factor)

MacOS 11.2 & 11.3 Developer Beta 1
Installing MacOS 11.3 Beta 2 now... will be back to say if that changed anything as that fixes a lot of bugs existent on Big Sur right now.

**Comment by Bryghton42** [comment]
> - Save a Custom Color does not work at all
> 
> - Selecting a custom color does not work at all
> 
> - In the Set a Custom Color window, the secondary custom color tab is unresponsive to selection
> 
> - Set a Custom Color window will only appear if attempting to select a custom color for all devices
> 
> - Add Custom Color to individual Devices does nothing
> 
> - Add Custom Color for all devices adds a color to the list, but does not bring up the Set a Custom Color Window unless attempting to select
> 
> 
> 
> Note: This issue has been happening on multi versions: v0.3.2, v0.3.5, & v0.3.6 -possibly more, but these are all that I have checked. All other lightning functions work.
> 
> Razer Equipment:
> 
> 
> 
> - Deathadder Elite (had for all 3 versions this was happening on)
> 
> - Core X Chroma (had for all 3 versions this was happening on)
> 
> - Huntsman v2 Analog (issue was happening before I received it today, so its support not being added yet is not a factor)
> 
> 
> 
> MacOS 11.2 & 11.3 Developer Beta 1
> 
> Installing MacOS 11.3 Beta 2 now... will be back to say if that changed anything as that fixes a lot of bugs existent on Big Sur right now.

Try changing to another on board profile and changing the colors again. It works for newer devices like my razer mamba wireless.

**Comment by WrathofthePast** [comment]
I tried your solution on my Razer Deathadder v2 (2019) [replaced the Deathadder Elite], but no luck. The Core X Chroma does not have on board profiles and while the Huntsman v2 Analog has them, it isn't supported yet. Installing the latest beta did nothing either, but wasn't exactly expecting it to.

**Comment by WrathofthePast** [comment]
Just saw the v0.3.7 release. I did some testing with it and the custom color now works with the Core X Chroma. It still didn't work on the Deathadder v2, but trying your troubleshooting tip again got it working as well. I can't test the Deathadder Elite as it died a couple weeks ago, but I presume it would have worked too now. Huntsman v2 Analog support hasn't been added yet, so no surprise it doesn't do anything. I am closing this issue now.
