### ISSUE TITLE
Feature to change polling rate of mice

### ISSUE THREAD

**Issue by Harikeshav-R** [1kc/razer-macos#261]
Hello there!
I just recently bought a Razer DeathAdder Essential from Amazon with a no-return policy.
I was very excited to use it. I plugged it in and opened a game.
Whenever I move my mouse, there were HUGE lag-spikes.
I searched the net and found that it was due to WIndowServer.
The solution to this problem was to change the polling rate of the mouse from the default (1000hz) to a lower value (like 125hz)
But, Razer Synapse 2 does not support my mouse and I can't find a solution to this problem.
Im using an office mouse for now, so any help would be appreciated.
If this is not possible, please recommend an alternate solution to this problem that I am facing.
I am pretty sure that lots of other people have this problem, and this is one of the most versatile software for configuration of Razer peripherals.
I hope someone will respond to this!
Thank you for your time.

**Comment by Harikeshav-R** [comment]
Can someone at least suggest an alternative?
Please?
I'm desperate

**Comment by dhobi** [comment]
Hi there

You said you are using Windows as your operating system, can't you just use Razer Software to configure the DPI?

http://drivers.razersupport.com//index.php?_m=downloads&_a=view&parentcategoryid=131&pcid=11&nav=0,76,168,11

The thing is that this project is for macOS only. If it's all about setting the device up and you don't care about installing another OS (maybe in a VM) you could also try openrazer with Linux.

**Comment by Harikeshav-R** [comment]
No, I am on macOS.
A process called "WindowServer" is causing huge lag spikes when I move the mouse.

"WindowServer is a core part of macOS, and a liaison of sorts between your applications and your display. If you see something on your Mac's display, WindowServer put it there. Every window you open, every website you browse, every game you play—WindowServer “draws” it all on your screen." - HowToGeek.com

So, is it possible to change polling rate on Razer-macOS?

**Comment by dhobi** [comment]
Ahh sorry, I‘ve completely misunderstood this then. Yes, razer-macos let‘s you change the dpi (from 100-20‘000) given your mouse is supported.

**Comment by Harikeshav-R** [comment]
Is it possible to change the polling rate too?

**Comment by Bryghton42** [comment]
> Is it possible to change the polling rate too?
> 
> 

I don't know of any way that you could change the polling rate unless using a windows computer to change your profiles and then changing to them on Mac is. It works. To see if it worked go to a polling rate test online. Hope this helps!

**Comment by Harikeshav-R** [comment]
I tried what you said.
However, I bought a mouse that doesn't have on board memory profiles.
I don't know what to do now ......
(Before you say 'you should have checked if it was compatible on Mac', I did and the Amazon page said 'compatible with Unix and macOS)

**Comment by dhobi** [comment]
There is still hope. I've tried porting the polling rate feature here: https://github.com/1kc/razer-macos/pull/269
Once the PR is merged and a new version of razer-macos is built, you could try again.

**Comment by dhobi** [comment]
Polling rate should be changeable with the latest version (0.3.7). Could you verify this?

**Comment by Harikeshav-R** [comment]
Sorry, I have been off the internet for about 3 weeks (Well-deserved break :D).
Yes, seems like the feature works as intended.
Thank you so much! You might have saved me $50 as I can't return this mouse due to Amazon's electronic return policy.
Thanks for the quick fix as well!
I might sound informal now, but ilysm <3

**Comment by dhobi** [comment]
Can we close this issue then?

**Comment by Harikeshav-R** [comment]
Yeah, just wanted your response.
Thanks for a quick fix and keep up with this wonderful project!
