### ISSUE TITLE
Blackwidow tenkeyless v3 not can't find device

### ISSUE THREAD

**Issue by Jakkawad** [1kc/razer-macos#276]
Blackwidow ten keyless (green switch) v3 not can't find device on version 0.3.6

thx for fix it

**Comment by Jakkawad** [comment]
![Screenshot 2564-03-06 at 19 08 30](https://user-images.githubusercontent.com/12533828/110206289-60013300-7eaf-11eb-82b5-e984aa4f36b0.png)

**Comment by dhobi** [comment]
Taken from openrazer project: https://github.com/openrazer/openrazer/issues/1318

> If someone wants to look into implementing this, use the razer_chroma_extended_matrix_effect_* functions with ZERO_LED (you can also try BACKLIGHT_LED if that works), razer_chroma_extended_matrix_brightness for brightness (also ZERO_LED). For custom frame use razer_chroma_extended_matrix_set_custom_frame and MATRIX_DIMS = [6, 18] . For reference look at recent commits for razerkbd.

This sounds straightforward but I don't have the device to test the implementation.

**Comment by Jakkawad** [comment]
> Taken from openrazer project: [openrazer/openrazer#1318](https://github.com/openrazer/openrazer/issues/1318)
> 
> > If someone wants to look into implementing this, use the razer_chroma_extended_matrix_effect_* functions with ZERO_LED (you can also try BACKLIGHT_LED if that works), razer_chroma_extended_matrix_brightness for brightness (also ZERO_LED). For custom frame use razer_chroma_extended_matrix_set_custom_frame and MATRIX_DIMS = [6, 18] . For reference look at recent commits for razerkbd.
> 
> This sounds straightforward but I don't have the device to test the implementation.

![Screenshot 2564-03-06 at 19 17 45](https://user-images.githubusercontent.com/12533828/110206503-a905b700-7eb0-11eb-8077-c3118381785e.png)

I replace device id at huntsman te (same tkl model) 

![Screenshot 2564-03-06 at 19 18 53](https://user-images.githubusercontent.com/12533828/110206523-cf2b5700-7eb0-11eb-9500-1672f80452ac.png)

it work perfect 

possible to add lighting effects RIPPLE?

**Comment by dhobi** [comment]
Ripple effect will come soon thx to @stevenliuyi.

I'll close the other issues #259, #249, #88 in favor of this one.

**Comment by diogoverardi** [comment]
> > Taken from openrazer project: [openrazer/openrazer#1318](https://github.com/openrazer/openrazer/issues/1318)
> > > If someone wants to look into implementing this, use the razer_chroma_extended_matrix_effect_* functions with ZERO_LED (you can also try BACKLIGHT_LED if that works), razer_chroma_extended_matrix_brightness for brightness (also ZERO_LED). For custom frame use razer_chroma_extended_matrix_set_custom_frame and MATRIX_DIMS = [6, 18] . For reference look at recent commits for razerkbd.
> > 
> > 
> > This sounds straightforward but I don't have the device to test the implementation.
> 
> ![Screenshot 2564-03-06 at 19 17 45](https://user-images.githubusercontent.com/12533828/110206503-a905b700-7eb0-11eb-8077-c3118381785e.png)
> 
> I replace device id at huntsman te (same tkl model)
> 
> ![Screenshot 2564-03-06 at 19 18 53](https://user-images.githubusercontent.com/12533828/110206523-cf2b5700-7eb0-11eb-9500-1672f80452ac.png)
> 
> it work perfect
> 
> possible to add lighting effects RIPPLE?


I've also tried replacing the device ID to , and it worked perfectly fine as well!  
Looking forward for 0.3.7

**Comment by BenJaine** [comment]
Ive changed the device ID, how to I then get the code as a program, sorry im very new to this

**Comment by diogoverardi** [comment]
> Ive changed the device ID, how to I then get the code as a program, sorry im very new to this

@BenJaine 
Basically you just follow the Developer Usage section here: https://github.com/1kc/razer-macos#developer-usage

But step by step it would be:
1 - Download Xcode and install it (via AppStore)
2 - Install YARN (https://classic.yarnpkg.com/en/docs/install/#mac-stable)
3 - Clone this project locally
4 - Change the device ID and save the file
5 - Open terminal and go the project, for example, for me the command is: `cd /Users/diogoverardi/Downloads/razer-macos` 
6 - Run the following command: `yarn dev`

...and it should work! 
but if it doesn't let me know and I call help you with this! ;) good luck
