### ISSUE TITLE
Version 0.3.7 seems not compatible with Big Sur 11.1? Version 0.3.6 still works

### ISSUE THREAD

**Issue by Him-C** [1kc/razer-macos#283]
![Screenshot 2021-03-09 at 9 33 39 PM](https://user-images.githubusercontent.com/75711589/110478419-4ebe5d80-811f-11eb-9713-71e1a1072d1d.png)
![Screenshot 2021-03-09 at 9 33 53 PM](https://user-images.githubusercontent.com/75711589/110478431-50882100-811f-11eb-9183-995299f4115d.png)

**Comment by Suma-xy** [comment]
same problem, im using macOS 11.3 Developer Beta.

**Comment by Bryghton42** [comment]
Yeah me too but I'm on Catalina

**Comment by Bryghton42** [comment]
It says I need Big Sur for it

**Comment by Suma-xy** [comment]
it seems that the 0.3.7 version only runs on macs with M1 chips

**Comment by 1kc** [comment]
@Suma-xy @Bryghton42 @Him-C, looks like I uploaded the wrong file 😅. Please go to Release and download it again.

**Comment by 1kc** [comment]
Thanks for flagging this guys, closing. 
ARM64 also builds without failing now, feel like magic.
