### ISSUE TITLE
does not work on macOS mojave 14.6.0

### ISSUE THREAD

**Issue by plumpus** [1kc/razer-macos#284]
when I open the application it says "macOS razer only supports macOS software 10.0.0 or higher. i will try this with a older razer macOS software

**Comment by Suma-xy** [comment]
@plumpus This issue has already been fixed. Just reinstall Razer-macOS. 
You can also close this issue.

**Comment by dhobi** [comment]
*Reinstall => Re-download the dmg. It has been fixed by @1kc in the meantime. Reopen the issue if it's still not working for you.
