### ISSUE TITLE
M1 Mac build won't open

### ISSUE THREAD

**Issue by SideMatter** [1kc/razer-macos#289]
Hello,
The 0.37 release for the M1 Macs will not open. It gives this error.
<img width="255" alt="image" src="https://user-images.githubusercontent.com/33376632/110520584-e4c89880-80cb-11eb-9b21-a57f8f749817.png">

M1 MacBook Pro, 0.37, macOS 11.2.2 (20D80).

Let me know if I can debug or help in any way

**Comment by diogoverardi** [comment]
Same issue here for release 0.3.7
M1 Mac mini, MacOs 11.2.2

**Comment by 1kc** [comment]
Hi @diogoverardi, @SideMatter. Please try the latest release (0.3.8) and see if the M1 version works. Note that you should be downloading the Razer.macOS-0.3.8-arm64-M1-Macs.dmg file. 

If it still doesn't work, you can keep using the normal Intel version. In that case I guess M1 building is still broken from my Intel laptop.

**Comment by diogoverardi** [comment]
Hi @1kc Thanks for having a look into this! 

I've just tried and same error occurs
![Screen Shot 2021-03-11 at 10 03 46 AM](https://user-images.githubusercontent.com/30538676/110807614-38b0ba00-8251-11eb-915d-c0501ce84883.png)

I'll clone the repo, and try to compile it to see what happens!

**Comment by 1kc** [comment]
Please do!

**Comment by diogoverardi** [comment]
@1kc Had an issue running the `yarn` command 
![Capture d’écran, le 2021-03-12 à 00 02 16](https://user-images.githubusercontent.com/30538676/110894708-54a27300-82c6-11eb-8369-9ab44e8a034f.png)

That's because there's no such release for the arm64 here [iohook repo](https://github.com/wilix-team/iohook/releases)
And I was able to workaround this by removing the arm64 from the iohook>arches(line94) in the _package.json_ 
and after removing it, I was able to run the `yarn dev` and get the app running, but there's a bug... as expected. since it's using the x64iohook.

**All options, effects, custom colors, brightness are all working fine,** but this error pops up when I try to use the Ripple effect:
![Capture d’écran, le 2021-03-12 à 00 11 30](https://user-images.githubusercontent.com/30538676/110895458-d050ef80-82c7-11eb-8673-d63122a3cb7b.png)
Here's the full content of the screenshot:
```
Uncaught Exception:
Error: Cannot find module '/Users/diogoverardi/Documents/razer-macos/node_modules/iohook/builds/electron-v85-darwin-arm64/build/Release/iohook.node'
Require stack:
- /Users/diogoverardi/Documents/razer-macos/node_modules/iohook/index.js
- /Users/diogoverardi/Documents/razer-macos/dist/main/main.js
- /Users/diogoverardi/Documents/razer-macos/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
at Module._load (internal/modules/cjs/loader.js:848:27)
at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/Users/diogoverardi/Documents/razer-macos/node_modules/iohook/index.js:10:21)
at Module._compile (internal/modules/cjs/loader.js:1152:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
at Module.load (internal/modules/cjs/loader.js:992:32)
```

I'm able to check this more in depth tomorrow, but this is what I found, I hope is helpful!

**Comment by dhobi** [comment]
Thanks, this is very helpful!
How should we proceed from here though? On one hand I don't like to have different builds with different features on the other I don't want to remove the cool ripple effect?!
- Wait for iohook to come up with an arm64 build? (https://github.com/wilix-team/iohook/issues/257)
- Try to find and replace iohook with an alternative working for x64 and arm64?

**Comment by stevenliuyi** [comment]
@diogoverardi @dhobi I manually built arm64 version of iohook on my M1 Mac, and it actually worked when I run `yarn dev`.

However, I noticed that when I used the arm64 version of node to run `yarn dist`, only the arm64 build worked. Similarly, when I used the x64 version of node, only the x64 build worked. Then I found out that it's because `iohook` uses `process.arch` to determine which version to use. I'm not very familiar with `electron-builder`, is there a way to build both targets simultaneously?

**Comment by 1kc** [comment]
@stevenliuyi Good investigating. I'm happy to build both versions independently for releases if you let me know the steps.
I also have a x64 Mac, I am assuming cross-compiling also works fine with your approach?

**Comment by stevenliuyi** [comment]
@1kc Here are what I did:
* Clone iohook's repository and run `yarn` to install dependencies
* Run `node -p process.arch` to make sure it's an arm64 version of node, and then use `yarn build --runtime=electron --version=11.0.0 --abi=85` to build arm64 version of iohook. There should be two built files `iohook.node` and `uiohook.dylib` in the folder `build/Release`
* Back to razer-macos's folder. Remove `arm64` from `iohook` >  `arches` in `package.json` so that `yarn` command can be run without error
* There should be a folder `electron-v85-darwin-x64` inside `node_modules/iohook`. Copy the folder and rename the copied one as `electron-v85-darwin-arm64`. Replace the two files `iohook.node` and `uiohook.dylib` in `electron-v85-darwin-arm64/build/Release` with the two files built previously

It should be good then. Running `yarn dist` now should build the arm64 version correctly. If we then switch to a x64 version of node (I installed both arm64 and x64 versions using nvm) and run `yarn dist` again, the x64 version can also be built.

**Comment by 1kc** [comment]
Thanks for that quick write-up. I don't think I can install the arm64 version of node using `nvm` since my laptop is only x64 unfortunately.  😞
Can you confirm the x64 version works on M1 devices? Although it's not native.

**Comment by stevenliuyi** [comment]
Yes, the x64 version works on M1 devices. I'm also willing to build M1 native version for releases until there is a better solution.

**Comment by 1kc** [comment]
I guess the ARM versions just provides a small performance benefit since it’s native? 
I am hoping that it will be solved once we have iohooks arm64 binaries.

**Comment by stevenliuyi** [comment]
Yes, there are no noticeable differences between the two versions.

On another note, I found a way to manually build arm64 iohook on my x64 device. Then I modified iohook's source code to force it to use the arm64 version, and then tried to cross-compile arm64 build on the x64 device. However the build didn't work on my M1 device, and I'm not quite sure what went wrong.

**Comment by sgulls** [comment]
I think I got it to work. check out the latest PR I hacked together.

make sure you set  `APPLE_USER` and `APPLE_PASS`/app password corresponding to your apple developer account in `release.sh` or export to your environment.

**Comment by 1kc** [comment]
Hey @sgulls, nice just saw your PR. I don't have an Apple developer account, is there a way around this when building. I understand there will be a security prompt for the users when they open the app.

**Comment by sgulls** [comment]
because it's a universal build of an electron app (electron apps are already chonky) the .dmg weighs in at 158 MB and the app bundle 401 MB, effectively just the two app bundles glued together with `lipo`

**Comment by sgulls** [comment]
for x86_64 yes, gatekeeper bypassing has been trivial but for arm64, binaries must be code signed (can be with a free dev account or even an ad-hoc self sign) AND notarized (requires paid dev account)

the only way to run unsigned apps on arm64 is to go into `1TR`/bootloader and lower security settings either with the GUI or `bputil`. Lowering the settings will cause Apple Pay to be disabled as well as the ability to run iOS apps. The only exception is designating your terminal as a "developer program" so you can run terminal programs through it but other than that, there is no way except to degrade security through `1TR`. I think

I'm probably wrong so someone feel free to correct me

**Comment by 1kc** [comment]
Guess I wouldn't be able to build the arm64 version for releases unless I have a paid dev account then?

**Comment by sgulls** [comment]
I mean it'll be technically compatible but macOS will not allow it to be run. Though ad-hoc signing *might* be enough `codesign -s - filename`

I'll have to try it out. 

I can cobble together a version of the build script that disables code signing and/or notarization though I'm not used to javascript so it really will be quite primative

**Comment by sgulls** [comment]
worst case, someone using the unsigned app bundle will have to run the x86_64 code in Rosetta as the code signing requirements aren't as strict for translated binaries while those who have a dev account or have already downgraded their security can run native arm64. at worst. 

(strongly recommend against changing the default security settings. even when I do it, it's for a temporary and specific reason that I immediately revert.)

**Comment by sgulls** [comment]
@1kc you just have to sign it using an ad-hoc certificate. Updated my branch and PR.

**Comment by sgulls** [comment]
build tested working on both x64 and arm64.

**Comment by sgulls** [comment]
https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma114/v4/02/d3/dc/02d3dc60-a78a-b3cc-e248-0ef1c54ecf37/developer_log.json?accessKey=1617278053_4427944477151190264_huHEbomuUbIyb74Sd0gVy4a+rMCuIVK0R9BqDBomoSq8SJibBki3W1KPu0Zty2L3s8drw9dXCwuITCi7c5/ulZof74yn98LyUPCB8zCywwOxRC8itY/oWPh9inQkBPb1PN1xdaNZTUUb1A0m4kQobTjfjCY+8XAmhI1mmJgSFaM%3D

**Comment by 1kc** [comment]
I've built it successfully on my x64 laptop and uploaded the new dmg here: https://github.com/1kc/razer-macos/releases/tag/v0.4.0
Please let me know if there are issues

**Comment by sgulls** [comment]
```
Uncaught Exception:
Error: Cannot open /Applications/Razer macOS.app/Contents/Resources/app-arm64.asar/addon.node: Error: dlopen(/var/folders/1p/pp5409b544l4htjs66ksblx00000gn/T/.com.electron.razer-macos.Qk0iZW, 1): no suitable image found.  Did find:
/var/folders/1p/pp5409b544l4htjs66ksblx00000gn/T/.com.electron.razer-macos.Qk0iZW: mach-o, but wrong architecture
/var/folders/1p/pp5409b544l4htjs66ksblx00000gn/T/.com.electron.razer-macos.Qk0iZW: stat() failed with errno=17
at Object.<anonymous> (/Applications/Razer macOS.app/Contents/Resources/app-arm64.asar/webpack:/build/Release/addon.node:1:159)
at Object.call (/Applications/Razer macOS.app/Contents/Resources/app-arm64.asar/main.js:1:1674)
at require (/Applications/Razer macOS.app/Contents/Resources/app-arm64.asar/webpack:/webpack/bootstrap:19:22)
at Module.call (/Applications/Razer macOS.app/Contents/Resources/app-arm64.asar/webpack:/src/driver/index.js:4:16)
at require (/Applications/Razer macOS.app/Contents/Resources/app-arm64.asar/webpack:/webpack/bootstrap:19:22)
at Object.call (/Applications/Razer macOS.app/Contents/Resources/app-arm64.asar/webpack:/src/main/index.js:3:25)
at __webpack_require__ (/Applications/Razer macOS.app/Contents/Resources/app-arm64.asar/webpack:/webpack/bootstrap:19:22)
at Object.call (/Applications/Razer macOS.app/Contents/Resources/app-arm64.asar/main.js:1:1442)
at __webpack_require__ (/Applications/Razer macOS.app/Contents/Resources/app-arm64.asar/webpack:/webpack/bootstrap:19:22)
at /Applications/Razer macOS.app/Contents/Resources/app-arm64.asar/webpack:/webpack/bootstrap:83:10
```

**Comment by sgulls** [comment]
weird I've ran the build from both arm and x64. I could upload my signed dmg for now if that helps

**Comment by 1kc** [comment]
Yeah that's strange. I've just run the release.sh script. 
Sure, if you could uploaded it here that would work for now.

**Comment by sgulls** [comment]
I can't upload it here as it's too big. Maybe if you gave me rights to only the release pages?

**Comment by 1kc** [comment]
It does run on my x64 machine, guess just not arm

**Comment by 1kc** [comment]
> I can't upload it here as it's too big. Maybe if you gave me rights to only the release pages?

Not sure if I could add that permission on Github? From my understanding, only owners can add files to the release page.
Google Drive etc would also work?

**Comment by sgulls** [comment]
https://drive.google.com/file/d/1yQ0Cmqz-jg0ajdhLvvj6brYYF3sx7oMq/view?usp=sharing

Yeah even my own build on x64 won't open on arm. It seems that only arm will build one for both until I figure out what's wrong

**Comment by 1kc** [comment]
> https://drive.google.com/file/d/1yQ0Cmqz-jg0ajdhLvvj6brYYF3sx7oMq/view?usp=sharing
> This was built and signed on arm
> 
> Yeah even my own build on x64 won't open on arm. It seems that only arm will build one for both until I figure out what's wrong

Thanks for that, I'll upload it. We've been trying to get it working for arm for a while and hopefully it works out this time.

**Comment by SideMatter** [comment]
I'll try opening that on my MBP M1 and see what happens

**Comment by sgulls** [comment]
*sigh* my bad it seems the problem is the other way around. tell you what I'll get you separate DMGs once I confirm they actually work on both here in a few mins

**Comment by 1kc** [comment]
> I'll try opening that on my MBP M1 and see what happens

Just uploaded

**Comment by SideMatter** [comment]
can confirm that this build https://drive.google.com/file/d/1yQ0Cmqz-jg0ajdhLvvj6brYYF3sx7oMq/view?usp=sharing opens and runs on the M1 MacBook Pro.

**Comment by sgulls** [comment]
separate builds is probably better anyways. 200 MB of dead weight is non-insignificant for some. 

@1kc please reupload these:

https://drive.google.com/file/d/1YJrbCJtwrUBxeT9pgSd8pZIZYhdZS53U/view?usp=sharing
https://drive.google.com/file/d/1OZN9Df6hYKQfwEJqO9AzIpIsH6ghjVc9/view?usp=sharing

**Comment by sgulls** [comment]
@1kc and remove the universal image for now, it only works on whatever I built it on.

**Comment by 1kc** [comment]
Yep done

**Comment by dhobi** [comment]
Hate to be the messenger of bad news. The newest Intel dmg fails to load iohook on my (very) old iMac with 10.13.6 when I try to activate ripple 😞 

Uncaught Exception:
Error: Cannot find module 'iohook'
Require stack:
- /Applications/Razer macOS.app/Contents/Resources/app.asar/main.js

**Comment by 1kc** [comment]
Thanks for letting me know @dhobi, I might just upload our v0.4.0 original binary for the x64 dmg

**Comment by sgulls** [comment]
@1kc I'm brand new to node and javascript so could you look at my arm64 branch in my fork and figure out how to use the local iohook binary? I thought I declared it properly in `package.json`.

I compiled each arch on their respective machines and `lipo`'d them together so there shouldn't be any cross compile weirdness for iohook itself I think
