### ISSUE TITLE
0.3.7: Mouse Bungee Not Recognized / Responding

### ISSUE THREAD

**Issue by billstevenson** [1kc/razer-macos#291]
I believe my mouse bungee started working in 0.3.6, but now in 0.3.7 it's not seen despite the multiple accessory within category support.

Happy to provide logs if you tell me where to look.

**Comment by dhobi** [comment]
Is it this one:
src/devices/mouse_bungee_v3_chroma.json?

**Comment by billstevenson** [comment]
No worries! Thanks for looking at it so fast!

**Comment by 1kc** [comment]
legend! Hope its fixed

**Comment by billstevenson** [comment]
Verified resolved in 0.3.8
