### ISSUE TITLE
cannot change lighting effect to anything else once changed to Ripple effect

### ISSUE THREAD

**Issue by rohitkumar91** [1kc/razer-macos#292]
Once ripple effect is selected, I am not able to change the lighting effects to spectrum/breath/anything else or even None for that instance.
Whenever I connect my keyboard to Mac it automatically is set to the ripple effect since then.

How can I undo the effect and changer it back to default (spectrum)?

- Note: I have tried selecting the "Clear all settings option" to see if any of the default setting is set back in place. But there is no change.

**Comment by dhobi** [comment]
I can't reproduce the issue of not being able to switch back to another color mode. While testing I encountered the issue of not being able to activate Ripple more than once without restarting the app.
I guess we have some issue with properly restarting iohook.
