### ISSUE TITLE
Create documentation for implemented device feature

### ISSUE THREAD

**Issue by dhobi** [1kc/razer-macos#293]
Starting with 0.3.7, contributors can now configure the features of a device individually.

The updated wiki page should help to understand how to do this: https://github.com/1kc/razer-macos/wiki#device-feature-explanation

Let me know what you think / where I could further improve it.

Thanks!

**Comment by 1kc** [comment]
Docs look great!

**Comment by dhobi** [comment]
Ok, I'll close this for now.
