### ISSUE TITLE
Cannot find Base Station V2 Chroma

### ISSUE THREAD

**Issue by arubatoor** [1kc/razer-macos#294]
Once i open the app it tells me to select a device to configure. I plug my v2 chroma into my mac and it cant find it. Can anyone help me with this issue?

**Comment by dhobi** [comment]
This does not sound right at all as this "Select a device to configure" window should not be visible (if you do not try to start the app twice).
Razer macOS is mainly a "Tray" app, meaning if you start the application you won't have an application in the dock or a window but just the Razer macOS logo in the menu bar at the top right. From there you should be able to select and configure a device.

I hope this helps!

**Comment by dhobi** [comment]
I'm thinking about adjusting the text from "Select a device to configure" to something like "Select a device from the menu bar" to make this more clear for future users.

**Comment by arubatoor** [comment]
Helped a lot!! Thanks so much!
