### ISSUE TITLE
Razer Huntsman elite not detected on Mac big Sur OS

### ISSUE THREAD

**Issue by daljeet-singh** [1kc/razer-macos#297]
I am trying to connect my razer huntsman elite keyboard, but it is not detected in my mac big sur OS

**Comment by 1kc** [comment]
It should be supported. Does it show up in the menu?

You could also try previous versions to see if you have better luck.

**Comment by daljeet-singh** [comment]
Yes, it started showing up in my menu. after reconnecting the device. Thanks
