### ISSUE TITLE
Show ' ⌘Q '  shortcut in menu 

### ISSUE THREAD

**Issue by Suma-xy** [1kc/razer-macos#299]
Hello there. Is it possible to display the ⌘Q shortcut in the menu? I have designed and linked an example. 

On the one hand it helps many who do not know the shortcut, on the other hand it looks much better.

<img width="900" alt="Bildschirmfoto 2021-03-15 um 11 05 34" src="https://user-images.githubusercontent.com/48092912/111136914-83e30980-857e-11eb-810b-61dd4c82627c.png">

**Comment by 1kc** [comment]
TODO

**Comment by 1kc** [comment]
Done!
