### ISSUE TITLE
Error message when quitting Razer-macOS on Intel

### ISSUE THREAD

**Issue by Suma-xy** [1kc/razer-macos#300]
Thanks for the last update, it's amazing. Unfortunately since then I get an error message when I exit Razer-macOS. I have restarted my Mac, reinstalled Razer-macOS and deleted all settings. None of this has helped.
I use a MacBook Pro with an Intel processor.

https://user-images.githubusercontent.com/48092912/111138079-d1ac4180-857f-11eb-9fed-eba3a0733b3f.mov

**Comment by 1kc** [comment]
Thanks for reporting this. Should be fixed in [v0.3.9](https://github.com/1kc/razer-macos/releases/tag/v0.3.9)

**Comment by Suma-xy** [comment]
Thank you, I no longer get the error message :))
