### ISSUE TITLE
[Question] Why does ripple require accessibility access while reactive does not?

### ISSUE THREAD

**Issue by Zfauser** [1kc/razer-macos#302]
I was just wondering why the reactive effect does not need accessibility access while ripple does?

**Comment by dhobi** [comment]
The reason for this is how the Ripple effect is implemented. In contrary to the reactive effect it's completely "Software driven":

It uses iohook (this one request accessibility acces) under the hood to listen to keypresses and sends calculated custom frames (color values for each single key) to the razer device.

Reactive effect is almost the whole opposite (hardware). All we tell is "enable reactive mode with color x and speed y". The keypress listening and animation is done completely on the device itself.

I hope this clarifies it a bit.

**Comment by Zfauser** [comment]
Thanks for the clarification!
