### ISSUE TITLE
Stuck on the first screen "please select a device to configure"

### ISSUE THREAD

**Issue by psychicfemme** [1kc/razer-macos#303]
As of posting this, i have downloaded the latest version. How do I select my device?
<img width="498" alt="Screen Shot 2021-03-15 at 4 20 43 PM" src="https://user-images.githubusercontent.com/80718192/111216138-66c43000-85aa-11eb-8f14-17c267596ec5.png">

**Comment by altjx** [comment]
@psychicfemme why'd you close this? Did you fix it? If so, what'd you do? I'm having the same issue.

**Comment by ulavie** [comment]
hi @altjx , i have the same problem, what did you do to fix it?>
thanks

**Comment by dhobi** [comment]
Same as #391 ?
