### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by fishcharlie** [1kc/razer-macos#318]
@1kc Love this project. Would love to donate for your work to this project. Any chance you'd be willing to provide some method for donation (GitHub Sponsors, cryptocurrency addresses, OpenCollective, or something along those lines)?

**Comment by daljeet-singh** [comment]
+1

**Comment by 1kc** [comment]
Thanks for the love!
Would be good to have some sort of community bug bounty donation thing in the future.  Not for me personally since I can't take credit for all the community/team's work haha.

**Comment by 1kc** [comment]
Ok you can now fund new features/issues through the 'Sponsor' button!
