### ISSUE TITLE
Razer Kraken Kitty Edition shows broken image

### ISSUE THREAD

**Issue by ScarlettHoefler** [1kc/razer-macos#324]
I just updated to version 0.3.9. When I open the menu to the Razer Kraken Kitty Edition, it shows a broken image in the top left of the UI:

![Screen Shot 2021-03-24 at 7 22 16 PM](https://user-images.githubusercontent.com/1617436/112409551-efdc1500-8cd6-11eb-8d06-20e58c1f3fba.png)

My Razer Mouse Charging Dock, however, did show the image for that device, so I am guessing it's something device specific.

**Comment by dhobi** [comment]
Will be fixed with 0.4.0 (https://github.com/1kc/razer-macos/commit/fca5ba776ee9b11152575595920cef9f83f923ca)

**Comment by dhobi** [comment]
@ScarlettHoefler Can you confirm that the image is shown for the Kraken Kitty Edition with 0.4.0?

**Comment by ScarlettHoefler** [comment]
Yep, looks like it's working now! Attaching a screenshot just for reference. Thanks for the fix!
![Screen Shot 2021-04-03 at 10 20 39 PM](https://user-images.githubusercontent.com/1617436/113499477-149c6d80-94cb-11eb-8bc9-53dda532df5f.png)
