### ISSUE TITLE
Support keyboard Razer Blackwidow Tournament Chroma V2

### ISSUE THREAD

**Issue by HiagoAdao** [1kc/razer-macos#327]
Please, can you give support for the Razer Blackwidow Tournament Chroma V2 keyboard?

Thank you guys!

**Comment by dhobi** [comment]
I think the device should already be supported (0x0209). It will just be listed as "Razer BlackWidow Chroma Tournament Edition" in the tray at the top right.

**Comment by HiagoAdao** [comment]
Thanks @dhobi!
