### ISSUE TITLE
Starlight - Blackwidow Elite

### ISSUE THREAD

**Issue by avigucci** [1kc/razer-macos#330]
Whenever trying to use starlight an error pops up. Hopefully, this can be fixed in the next update.
thanks :)
![Screen Shot 2021-03-28 at 7 29 59 PM](https://user-images.githubusercontent.com/75952780/112776145-0f877c00-8ffc-11eb-953e-8a9d0dae63e1.png)
![Screen Shot 2021-03-28 at 7 30 07 PM](https://user-images.githubusercontent.com/75952780/112776146-10b8a900-8ffc-11eb-99cf-adf1283c3405.png)

**Comment by 1kc** [comment]
Please download the latest release file for 0.4.0 and try again

**Comment by avigucci** [comment]
That worked, thanks :)
