### ISSUE TITLE
Razer Ornata Chroma V2 Ripple Effect Not Working!

### ISSUE THREAD

**Issue by ZaneMorningstar30** [1kc/razer-macos#334]
I'm having an issue on the Razer  MacOS version 0.4.0 I think it is and I'm using a Razer Ornata Chroma V2 and when I choose to use the ripple effect it does nothing and turns all of the RGB Lights on my keyboard completely off but when I choose other options like wave or static custom color it does juts fine please fix the ripple effect thanks!

**Comment by 1kc** [comment]
Was it working previously in v0.3.9 etc?

**Comment by ZaneMorningstar30** [comment]
Yeah I think it used to work not really sure but currently on 0.4.0 every effects works just fine except for the ripple effect. Hope there is a fix soon because I don't want to have to downgrade back to 0.3.9 Thanks!

**Comment by 1kc** [comment]
Please get the latest Razer.macOS-0.4.0.dmg. 

Ripple was broken yesterday but it should be resolved now.
