### ISSUE TITLE
Non Applicable Brightness Settings for Razer Mice with Two Zones

### ISSUE THREAD

**Issue by WrathofthePast** [1kc/razer-macos#340]
In v0.4.0 as well 0.3.7-9, there are "Left Side" & "Right Side" brightness settings after the "Logo" and "Scroll Wheel" Brightness settings. It is unclear what they do and I am unsure whether they apply to Razer Deathadder v2, but given that they do not have any affect on it, they probably don't apply to it.

**Comment by twistedpixel** [comment]
Doesn’t seem to do anything for Basilisk Ultimate either. Are we sure it’s working correctly? Which devices have been tested with this feature?

**Comment by WrathofthePast** [comment]
Deathadder v2 & Deathadder Elite. Is the Basilisk Ultimate 3 or 4 zones? If it's 3, then that's likely a bug for that model. The Mamba Elite has left and right lights on top of the normal scroll wheel and logo lights. That's the only model I could find that has 4 zones assuming the Basilisk Ultimate has 3.

**Comment by twistedpixel** [comment]
Basilisk Ultimate is 4 I think. Logo and scroll obviously count for two, then there’s the strip along the left side which makes 3 and the 4th is a smaller strip along the right (under the right button).

**Comment by WrathofthePast** [comment]
I saw that it has 4 lights, but it's unclear whether it's 3 or 4 zones. In other words, whether the ability to control those brightnesses separately exists or not. Are you able to check on official Synapse on Windows? Also, did the v0.4.1 make any difference with it for you?

**Comment by WrathofthePast** [comment]
Others in #328 seem to have the same problem as you. However, these remain separate issues as the Deathadder v2 & Deathadder Elite should not have those "left" & "right" brightness settings.

**Comment by nightsky30** [comment]
> I saw that it has 4 lights, but it's unclear whether it's 3 or 4 zones. In other words, whether the ability to control those brightnesses separately exists or not. Are you able to check on the official Synapse on Windows? Also, did the v0.4.1 make any difference with it for you?

All three Lancehead models, the Mamba Elite, and I believe the Basilisk Ultimate all have 4 zone LEDs. But they should also have individually addressable LEDs for the LEDs on the side strips. There **might** be a few newer Naga models that make use of the left/right zones as well.

And as you're saying, yeah does not appear the Deathadder v2 and Deathadder Elite have these zones.

**Comment by twistedpixel** [comment]
> All three Lancehead models, the Mamba Elite, and I believe the Basilisk Ultimate all have 4 zone LEDs. But they should also have individually addressable LEDs for the LEDs on the side strips.

This is correct. The left side strip of my Basilisk Ult has at least 3 different LEDs which can be simultaneously different colors.

**Comment by WrathofthePast** [comment]
So besides this feature not working on those models properly, it remains as extra settings on many mice models that don't have 4 zones, so the settings shouldn't appear for those.

**Comment by dhobi** [comment]
The mouse brightness feature is "designed" to show all 4 options per default. However, it can be configured by device to only show a subset of those 4 options. I was just very lazy so far 🙁 

I think it should be possible to configure it properly by having a look at the openrazer mouse python classes as they (should) contain the programmable LED per device.

**Comment by WrathofthePast** [comment]
Sounds good, but no rush though. Also, don't feel bad as this isn't very important in terms of the whole project- I was just confused on what those were before. Thank you.

**Comment by WrathofthePast** [comment]
In v0.4.3-test, the non applicable brightness settings are removed, so I am closing this issue under the assumption that the next release will be the same.
