### ISSUE TITLE
Support for Razer Thunderbolt 4 Dock Chroma

### ISSUE THREAD

**Issue by rummeyer** [1kc/razer-macos#341]
Please add support for Razer Thunderbolt™ 4 Dock Chroma

**Comment by bradstimpson** [comment]
I second this - is there an ETA for support of this dock?

**Comment by Krebsgewehr** [comment]
Following this as well. Not sure how the new devices are added but If one is required to pull information to make the process easier I would do whatever I can to help move this along. Thanks for the hard work!

**Comment by SylvainRamousse** [comment]
+1

**Comment by dhobi** [comment]
Usually we wait for openrazer to do the hard work: getting the pcap, reading out the sent commands and do the coding. So, if you really really want to have this device supported as soon as possible: head over to openrazer, open an issue for Razer Thunderbolt 4 (I just have checked, they don't have one yet) and provide a pcap (Windows). 👍

**Comment by SylvainRamousse** [comment]
Thanks, I've opened an issue with info I can provide https://github.com/openrazer/openrazer/issues/1506

**Comment by SylvainRamousse** [comment]
hey there !

Support as just been added on openrazer ! https://github.com/openrazer/openrazer/issues/1506

Any hope for us, MacOS users ? :)

**Comment by JamIsJam88** [comment]
> Please add support for Razer Thunderbolt™ 4 Dock Chroma

+1

**Comment by Oberschmidt93** [comment]
Also looking forward to the Dock Chroma Support, only device left I can't control 🤞  Thanks for your work guys!

**Comment by rummeyer** [comment]
Fixed by https://github.com/1kc/librazermacos/pull/17
