### ISSUE TITLE
Ripple and Wheel for Blackwidow V3

### ISSUE THREAD

**Issue by pinkapoppy** [1kc/razer-macos#342]
Ripple effect had originally working (but buggy) during version 0.4.0, but both Ripple and Wheel both appear to be unavailable to select as an option for the Blackwidow V3 keyboard. Just wanted to check that this was intentional/if there are any plans in place for when these options will be accessible.
Thank you!

**Comment by 1kc** [comment]
This is definitely not intended. Thanks for letting me know, I’ll disable v0.4.1 until we have a fix.

**Comment by 1kc** [comment]
should be fixed in the reuploaded release file

**Comment by hannojg** [comment]
@1kc might need to reopen this. Having my Blackwidow v3 connected via wire and the ripple option is disabled.
