### ISSUE TITLE
it's not a problem but thanks you

### ISSUE THREAD

**Issue by yoy1mess** [1kc/razer-macos#35]
it's not a problem but thanks you, this new update is on point and im loving it, if it wasn't for you my razer keyboard and mouse wouldn’t look so incredible ( now im looking forwards to buy upa grade my mouse mat to an razer pd; you’re amazing and doing a great favor to the razer mac community)!!!! ❤️❤️❤️❤️

**Comment by 1kc** [comment]
Glad you've found it useful 😀❤️, it was a good team effort! @bournejc and @sourav-dey did some really fantastic work the last few days that brings it all together.

**Comment by yoy1mess** [comment]
Great team effort!!! @bournejc @sourav-dey @1kc
