### ISSUE TITLE
Version for Older Macs

### ISSUE THREAD

**Issue by Bryghton42** [1kc/razer-macos#358]
Can you guys please support older versions of Mac OS for this like high Sierra?

**Comment by dhobi** [comment]
I'm having no problem running razer macos on High Sierra (10.13.6). On which version are you?

**Comment by Bryghton42** [comment]
> I'm having no problem running razer macos on High Sierra (10.13.6). On which version are you?

I had no idea it would work. I assumed it wouldn't because you guys said Catalina and Big Sur. You should put (lowest version) and above. Thank you though.

**Comment by 1kc** [comment]
Thanks for that feedback
