### ISSUE TITLE
Wheel light mode colors are too white

### ISSUE THREAD

**Issue by Stanman04** [1kc/razer-macos#360]
Wheel light mode colors are too white

**Comment by dhobi** [comment]
Which Razer mouse are you using?

**Comment by Stanman04** [comment]
This is for the new keyboard effect, and I'm using the Razer ornate v2

**Comment by dhobi** [comment]
Ahh I see. 
I think we would have to make this user configurable in the future as there will always be someone thinking it looks too dark/light or too intense/washed out when we change it globally. Currently it's hardcoded and set to hsv(angle,70%,100%).

**Comment by Stanman04** [comment]
possibly, just to clarify, its not that the color is too dark, or too bright, its the tint. Every color in the wheel looks like it would have passed through some white addition filter

https://user-images.githubusercontent.com/76707975/115907522-9dedf280-a42e-11eb-98ae-7a81cae7770a.mov

video attached

**Comment by Stanman04** [comment]
see the difference?  the wheel light mode looks too white

**Comment by dhobi** [comment]
Yes, I see what you mean. This is exactly what the saturation parameter does: it starts to look "washed out" or how you call it "like it went through a white filter". To fit the wave effect more, I've set the saturation to 100% now.
It should look better in the upcoming version (0.4.2) 😄

**Comment by Stanman04** [comment]
Thanks a lot man!

**Comment by dhobi** [comment]
@1kc just released 0.4.2. Give it a try. The wheel animation colors should no longer have the whiteish look.

**Comment by Stanman04** [comment]
Dreams like a dream. I guess second time's the trick. Thanks a lot man!

**Comment by Stanman04** [comment]
*works

**Comment by dhobi** [comment]
Great! I guess we can close this issue then. 😄
