### ISSUE TITLE
macOS Big Sur v11.2.3 (20D91) NOT recognising BlackWidow v3 Pro

### ISSUE THREAD

**Issue by 0dinator** [1kc/razer-macos#362]
macOS Big Sur v11.2.3 (20D91) NOT recognising BlackWidow v3 Pro. 
I have downloaded the app, opens, but does not recognise that there is a device connected. Have tried with cable, 2.4 and BT connection. 

Any suggestions? 

Thanks in advance :)

**Comment by dhobi** [comment]
Hi,

BlackWidow V3 Pro is not yet supported by Razer macOS and we already have an open issue here: #151
I suggest to track the progress there!
