### ISSUE TITLE
Razer Blade 15 2020 Base Support

### ISSUE THREAD

**Issue by LuxuryWasTaken** [1kc/razer-macos#363]
Hey I know someone already pulled a request about it, the reason I'm creating new one to show there is more Razer Blade users in community.

Razer Blade 15 2020 base coming RGB as default so it's kinda disgusting, I want to set it to static white.

The main driver you guys are using added Razer Blade 15 2020 Base support recently, when we can get it on macOS?

**Comment by dhobi** [comment]
> Hey I know someone already pulled a request about it, the reason I'm creating new one to show there is more Razer Blade users in community.

While I do think that you created this issue with good intentions in mind, you could write this all in the already existing issue as a comment. This will not only make sure that all information/progress is kept in once place but saves us some work in administrating the open issues. 👍 

> The main driver you guys are using added Razer Blade 15 2020 Base support recently, when we can get it on macOS?

I guess you know the answer already: Until someone finds time to implement it. 🙂 We are all doing this in our free time.

I'll close this issue now in favor of #356. Let's track the progress there.
