### ISSUE TITLE
Cynosa Chroma Pro - Not working

### ISSUE THREAD

**Issue by DavidJamesAustin** [1kc/razer-macos#365]
My Cynosa Chroma Pro keyboard will not work, even after refreshing/uninstalling/restarting. Any suggestions on how to get it to pick up? I've also tried playing around with the USB port. Is it because I am using a USB-C adapter? I've also tried another adapter to make sure that it wasn't specific to that one. Any ideas on how to fix this?

**Comment by dhobi** [comment]
Razer macOS has no support yet for Cynosa Chroma Pro. We have an open issue here: #275
I'll close this issue now in favor of #275. Let's track the progress there.
