### ISSUE TITLE
2.1 breaks Viper Ultimate dock

### ISSUE THREAD

**Issue by bournejc** [1kc/razer-macos#37]
2.1 seems to break the dock for my Viper Ultimate.   Sometimes the mouse is detected sometimes the dock is.  The problem is the dock is treated as the same device as the mouse.  They need to be separate devices.

I will work on this for a future release.

**Comment by sourav-dey** [comment]
Ya, I removed the dock completely. The master should have the fix. We need to make razeraccessory for that

**Comment by 1kc** [comment]
It seems like it hasn't been fully merged [upstream](https://github.com/openrazer/openrazer/pull/1152/files).

**Comment by bournejc** [comment]
Okay I have a PR ready to add mouse dock functionality.  We may consider adding other mice here if it will work.

**Comment by sourav-dey** [comment]
@bournejc I think all mouse dock is the same. My Basilisk Wireless dock also the same device Id: 0x007E

Can you please change the name to general dock like say: Razer Mouse Charging Dock or something if thats the case?

**Comment by bournejc** [comment]
@sourav-dey oh that's great!  Hopefully most if not all docks are the same.  I'll make the change.

**Comment by bournejc** [comment]
This has been resolved in the latest build.
