### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by Chris-Thoresen** [1kc/razer-macos#388]
Unable to fully uninstall on Mac OS using Big Sur 

Have attempted to uninstall twice with the latest update, unable to fully remove code (as the keyboard is still responsive even after uninstall) - Any ideas on where the code is to remove completely?

**Comment by lengland** [comment]
To remove the app, you should delete the app from Applications. 

To fully remove all the config that came with it, remove the following files
```
"~/Library/Preferences/com.electron.razer-macos.helper.Renderer.plist"
"~/Library/Preferences/com.electron.razer-macos.plist"
"~/Library/Saved Application State/com.electron.razer-macos.savedState"
```
_Taken from the Homebrew cask definition_

The keyboard will remain functional after removing and restarting the machine, but that's down to generic drivers on both  machine and keyboard

**Comment by 1kc** [comment]
You can also use [appcleaner](https://freemacsoft.net/appcleaner/)
