### ISSUE TITLE
Huntsman Elite can't remember Wheel light effect?

### ISSUE THREAD

**Issue by versbrian** [1kc/razer-macos#401]
Thank you for this work. This is a life saver!!!

I love the "Wheel" effect. However, when I unplug and plug my keyboard, the wheel effect doesn't display on my keyboard. 

The keyboard shows the previous effect I set (e.g. Static, Wave, etc.)

Is it related with onboard memory support issue?

**Comment by 1kc** [comment]
Wheel is one of the effects that is “software“ or generated by your computer. So it goes away after you unplugged it. So it’s not a memory issues. Unfortunately there’s no way to keep it one the device since it’s not built in.

**Comment by versbrian** [comment]
Got it. 
Thank u. 

從我的iPhone傳送

**Comment by glauesppen** [comment]
Maybe this can be closed
