### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by Arabguy123** [1kc/razer-macos#44]
Hello wonderful developers! Any possibilities in the future for this application to support the Firefly V2 Mouse Pad?

**Comment by courtneyannexo** [comment]
Hi, I have the same question!! Your program already supports my keyboard and mouse, so it would be amazing if the Firefly V2 Mouse Pad was supported as well! Love this so much!

**Comment by Arabguy123** [comment]
It would be so awesome if they could.

**Comment by dhobi** [comment]
Firefly V2 (0x0c04) should be supported in the meantime. Please reopen / create a new issue if that's not the case for you.
