### ISSUE TITLE
Razer macOS is damaged and can't be opened. No options on security preferences.

### ISSUE THREAD

**Issue by mrAnomalyy** [1kc/razer-macos#445]
Hi.
I have following error on trying open the app.
I have MacBook Air M1 (I downloaded last arm64 release file) and Mac OS 11.5.2. 
Any hints, please?

<details>
  <summary>Error on open</summary>

![image](https://user-images.githubusercontent.com/39645529/131805349-bcf721d5-039b-4406-a142-23817cb7f9d3.png)
</details>
<details>
  <summary>Security & Privacy</summary>

![image](https://user-images.githubusercontent.com/39645529/131806159-90bcb6f4-c265-4cc4-b5f7-6d07f136fd17.png)
</details>

**Comment by 1kc** [comment]
Thanks for that report. It was meant to be a test release. I’ll disable it for now.

On 2 Sep 2021, at 6:06 pm, mrAnomalyy ***@***.***> wrote:

﻿

Hi.
I have following error on trying open the app.
I have MacBook Air M1 (I downloaded last arm64 release file) and Mac OS 11.5.2.
Any hints, please?

Error on open

[image]<https://user-images.githubusercontent.com/39645529/131805349-bcf721d5-039b-4406-a142-23817cb7f9d3.png>

Security & Privacy

[image]<https://user-images.githubusercontent.com/39645529/131806159-90bcb6f4-c265-4cc4-b5f7-6d07f136fd17.png>

**Comment by 1kc** [comment]
Please try the previous version for now, until we find a fix

**Comment by 1kc** [comment]
https://github.com/1kc/razer-macos/releases/tag/v0.4.5

**Comment by mrAnomalyy** [comment]
> https://github.com/1kc/razer-macos/releases/tag/v0.4.5

@1kc, this version installs and runs but seems to lack support for my ProType keyboard and ProClick mouse. Can it be because of x86 build or that just means open razer does not support my devices?

**Comment by 1kc** [comment]
I think it’s just not supported yet. You could cross compare with the non-arm64 version?

**Comment by mrAnomalyy** [comment]
> I think it’s just not supported yet. You could cross compare with the non-arm64 version?

Sadly, don't have any x86 Macs around.

**Comment by 1kc** [comment]
You can run the x86 version on a M1 Mac I think.
