### ISSUE TITLE
Blackwidow 2019 - No ripple effect

### ISSUE THREAD

**Issue by Slapzzz** [1kc/razer-macos#45]
In the options there's no ripple effect for the Blackwidow 2019 but the rest works perfectly <3

**Comment by egpbos** [comment]
Same here, it's working perfectly (which is *awesome* btw, I was just about to return the keyboard because Synapse 2 nearly bricked my Mac, found out about this project just in time), except ripple is not available in the menu.

**Comment by 1kc** [comment]
Hi, thanks for reporting and I am glad you've found it useful. Unfortunately, the ripple effect is the only one that requires a software implementation rather than a hardware implementation. This means further work will need to be done. Hopefully this will get implemented in the future.

**Comment by egpbos** [comment]
Do you mean that it should be implemented upstream in the Linux version or do you think it makes sense to do it in this project itself? I may be tempted to look into it if you can give me some pointers about where to start.

**Comment by dhobi** [comment]
Ripple effect is available in the meantime.

**Comment by egpbos** [comment]
That is great news. However, I don't seem to be able to get it to work just yet. I gave the app the required accessibility permissions, but my keyboard lights just go dark when I set it to ripple. Any ideas on how to fix?

**Comment by egpbos** [comment]
Never mind, after restarting the app it works now ❤️
