### ISSUE TITLE
Razer Core Chroma

### ISSUE THREAD

**Issue by iodrift** [1kc/razer-macos#47]
It would be awesome if you could add support for the Razer Core Chroma :)

Thanks for what you do!

**Comment by ThomObarski** [comment]
+1 on this one.
 
Thanks for all the great work to do what Razer won't!

**Comment by sdanaher** [comment]
For real!  This is great to have... Razer Core Chroma would be awesome... the wave effect is so great in windows, wish we had in macOS!

**Comment by Rems38** [comment]
I need it too !!!

Do you need informations on core Chroma?
mine is 1532:0f1a

Thanks a lot for what you do, it's clearly something that Razer should have done...

**Comment by sfroment** [comment]
https://github.com/1kc/razer-macos/pull/117

**Comment by dhobi** [comment]
Razer Core X Chroma (0x0f1a) should be supported in the meantime. Please create a new issue if your Razer Core device is not working.
