### ISSUE TITLE
Deathadder Essential Support

### ISSUE THREAD

**Issue by YoruMaru** [1kc/razer-macos#477]
Doesn't recognise my deathadder essential mouse.

Once I've installed razer-macos and plugged in my mouse is there another step i must do? (tried refreshing device list and didn't work)

**Comment by WrathofthePast** [comment]
Just to be clear: it doesn't appear in razer-macos at all & you're on the latest version?

**Comment by YoruMaru** [comment]
> Just to be clear: it doesn't appear in razer-macos at all & you're on the latest version?

Unfortunately not. Further research suggested it's because i have a newer model.

**Comment by WrathofthePast** [comment]
Ah, I looked into it. I'll add the support for you... the newer version has a different PID. You'll have to test it though as I don't have that specific mouse. Can you do that?

**Comment by YoruMaru** [comment]
> Ah, I looked into it. I'll add the support for you... the newer version has a different PID. You'll have to test it though as I don't have that specific mouse. Can you do that?

Yes im happy to do that thank you so much!

**Comment by WrathofthePast** [comment]
Done. Here's a [download](https://github.com/WrathofthePast/razer-macos/releases), so you can test it. Lmk if it works.

**Comment by YoruMaru** [comment]
> Done. Here's a [download](https://github.com/WrathofthePast/razer-macos/releases), so you can test it. Lmk if it works.

it works! thanks so much man :)

**Comment by WrathofthePast** [comment]
You're welcome. Glad I could help.

**Comment by YoruMaru** [comment]
> You're welcome. Glad I could help.
