### ISSUE TITLE
Code signature is missing in version 0.4.6

### ISSUE THREAD

**Issue by suschizu** [1kc/razer-macos#491]
Hello there!
I've received a warning that the code signature is missing in version 0.4.6
>… ' EXPECTED Ville Karja (P55C5BCV2E) but FOUND (null)' (It's a selfmade script - nothing official)

Can you confirm this?
Thanks!

**Comment by core-code** [comment]
@1kc since this could indicate a breach of security could you explain why your latest release is completely unsigned - contrary to previous releases? thanks!

**Comment by 1kc** [comment]
> @1kc since this could indicate a breach of security could you explain why your latest release is completely unsigned - contrary to previous releases? thanks!

Sure @core-code. The previous release (v0.4.5) was signed by @overcurrent, who has an Apple Developer's license. This was the only release that was signed. I on the other hand do not have this license since it does cost $99 USD per year. Hence why you would need to go into Mac security setting to run it.

**Comment by core-code** [comment]
thanks a lot for the explanation!

> not have this license since it does cost $99 USD per year.

i thought Apple gave up that requirement a few years back and even free accounts can sign Mac software now and just submitting into the App Store costs...

**Comment by protoz** [comment]
Thanks for the heads up on 0.4.5 being signed so I could install it.  Luckily my kb/mouse are supported in that version (Nage Pro wasn't supported for quite awhile).

**Comment by overcurrent** [comment]
Letting you all know that release 0.4.7 is here and it's signed. You can get it here: https://github.com/1kc/razer-macos/releases/tag/v0.4.7

**Comment by suschizu** [comment]
great thanks - version 0.4.7 is correctly signed with "Ville Karja (P55C5BCV2E)" 🙌
