### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by peyxan123** [1kc/razer-macos#494]
I am receiving the attached error. I have tried uninstalling and trying again.
![Uploading Screen Shot 2021-11-19 at 4.29.37 PM.png…]()

**Comment by 1kc** [comment]
I can’t see the screenshot sorry?

**Comment by Jetjames95** [comment]
I have the same problem.

![Senza titolo](https://user-images.githubusercontent.com/66027498/142767237-2ba3464e-48e6-43c2-a71f-2c900b865eff.png)

**Comment by 1kc** [comment]
> I have the same problem.
> 
> 
> 
> ![Senza titolo](https://user-images.githubusercontent.com/66027498/142767237-2ba3464e-48e6-43c2-a71f-2c900b865eff.png)
> 
> 
> 
> 

I would suggest trying the older version and see if it works fine

**Comment by Jetjames95** [comment]
Version v0.4.5 on High Sierra (10.13) works for me (selecting the white profile fn + application key) with the Razer BlackWidow Elite keyboard but not with my Razer Naga Hex mouse and my Razer Kraken Ultimate headset. Is there anything I can do to help resolve this issue?

**Comment by ssjblue-xxx** [comment]
I FOUNDED HOW TO FIX GUYS you have to download version 0.4.5 (here is the link https://github.com/1kc/razer-macos/releases/download/v0.4.5/Razer.macOS-0.4.5-universal.dmg)
