### ISSUE TITLE
Deathadder V2 not showing up

### ISSUE THREAD

**Issue by DeVlaminckDuncan** [1kc/razer-macos#499]
I'm trying to get my Deathadder V2 mouse to work with this software but it won't show up. I've tried using the latest release and also tried building the app but none of them worked. I'm on a 2019 Macbook Pro (Intel CPU) and macOS Monterey 12.0.1.

**Comment by charisTheo** [comment]
Same for me for DeathAdder Essential

**Comment by WrathofthePast** [comment]
> Same for me for DeathAdder Essential

@charisTheo, how did you download the dmg prior to Nov 14th and/or build using the archive downloads? The original v0.4.6 release was an accidental rerelease of v0.4.5 which was resolved in #489, but only for the dmg (archives were not corrected). 

> I'm trying to get my Deathadder V2 mouse to work with this software but it won't show up.

@DeVlaminckDuncan, this wouldn't explain your issue as the DeathAdder V2 support was added before v0.4.6 and it works for me (I have the same mouse). However, try the following:
1. Make sure the light on the bottom of the mice is white (if not shuffle through the profiles till it is).
2. Press `Refresh Device List`

**Comment by DeVlaminckDuncan** [comment]
Found the issue, my mouse wasn't automatically selected even though it's the only Razer device connected to my laptop.

**Comment by WrathofthePast** [comment]
> Found the issue, my mouse wasn't automatically selected even though it's the only Razer device connected to my laptop.

@DeVlaminckDuncan, can this issue be closed then?
