### ISSUE TITLE
Mouse speed / DPI

### ISSUE THREAD

**Issue by sturze** [1kc/razer-macos#50]
Hi there!

I really love your Project! Thank you very much for your work!
Do you think it's possible to add something for changing DPI on mice like on the polychromatic Project?

i am gaming on Mac and don't see any options to handle my DPI settings...

**Comment by dhobi** [comment]
DPI and Polling rate are changeable in the meantime (v0.3.7+). Please reopen this issue if that's not the case for you.

**Comment by sturze** [comment]
> DPI and Polling rate are changeable in the meantime (v0.3.7+). Please reopen this issue if that's not the case for you.

AWESOOOMEE!!! I just checked! Thank you so much! This is getting better and better! I love it! Great Work! Keep going guys!

**Comment by frapana** [comment]
@dhobi DPI customization was available on Razer Basilisk Ultimate Receiver in 0.3.7 but I cannot see it anymore in the menu on 0.4.0

**Comment by dhobi** [comment]
@frapana 
Sorry, this might be a regression of https://github.com/1kc/razer-macos/commit/f9dedd7cc9ab3f79470bc4619341366892e36781
Can you create a new issue as this one is already closed?
"Missing DPI option for Razer Basilisk Ultimate Receiver in 0.4.0"

Thank you!
