### ISSUE TITLE
Black Widow V3

### ISSUE THREAD

**Issue by Vanillinzucker** [1kc/razer-macos#501]
So up until last night, setting a colour and an effect for the keyboard worked without a problem. However, it installed the new Monterey Beta and even though it shows the colour as set, the keyboard doesn't react to any changes at all.

**Comment by overcurrent** [comment]
Hello @Vanillinzucker, could you try if the recently released 0.4.7 solves this issue? You can get it here: https://github.com/1kc/razer-macos/releases/tag/v0.4.7

If it does, you could close this issue.

**Comment by Vanillinzucker** [comment]
Yes, it works! I'll close the issue now, thanks.
