### ISSUE TITLE
Support for Thunderbolt 4 Docking Station

### ISSUE THREAD

**Issue by hsnee** [1kc/razer-macos#516]
Hello, would it be easy to add support to the Thunderbolt 4 Docking station? https://www.razer.com/gaming-pc-accessories/razer-thunderbolt-4-dock/RC21-01690100-R3U1

I have both macOS and Windows (and good programming experience, though not in JS specifically) so let me know if I can help make this happen

**Comment by overcurrent** [comment]
Hi, version 0.4.8 brings Thunderbolt 4 Dock Chroma support: https://github.com/overcurrent/razer-macos/releases/download/v0.4.8/Razer.macOS-0.4.8-universal.dmg

Please give it a go and let me know how it works for you.

@1kc Please add the above dmg to this official upstream master release page under version 0.4.8 so others can download it easily.

**Comment by nickroberts** [comment]
I just downloaded and tested this. Seems to work as expected for the dock!

**Comment by overcurrent** [comment]
Hi, the release is now officially here: https://github.com/1kc/razer-macos/releases/tag/v0.4.8

I believe you could close this issue now.

**Comment by hsnee** [comment]
Works perfectly, thanks! Closing the issue
