### ISSUE TITLE
Stuck on "Please select a device to configure"

### ISSUE THREAD

**Issue by Snapengel** [1kc/razer-macos#522]
I might be retarded or something because I am lost. 

Just installed it on my Mac, following the instructions to a tee. 

Running the software results in me being stuck on a screen with the title's name. 

I don't have any options to find devices or refreshes (unless I'm just missing them?). 

Any advice would be very helpful, so thank you!

**Comment by Kief5555** [comment]
Same Issue here.

**Comment by 1kc** [comment]
You could download an older version and see if the issue still persists.

**Comment by Kief5555** [comment]
@1kc, I downloaded the one that supports Monterey (Because I am running it), still does not work
