### ISSUE TITLE
Stuck on "Select a device to configure" 

### ISSUE THREAD

**Issue by Kief5555** [1kc/razer-macos#523]
Hi, 

I am stuck on "Select a device to configure" Screen.
I tried an older version (0.3.6), still does not work
Edit: Just tried 0.3.0, does not work either. I also reset my NVRAM

macOS Monterey 12.1 (21C52)

Please help
<img width="899" alt="Screen Shot 2021-12-19 at 10 56 23 AM" src="https://user-images.githubusercontent.com/67562560/146687277-8e1d54e9-9740-4cd7-9790-fc29098b219c.png">
.

**Comment by WrathofthePast** [comment]
Continuation of #479 
> Hey, I tried that already. Didn’t work. I have the Razer Ornate Chroma. And the MSI DS100 Gaming Mouse.

Your mouse won't appear as razer-macos only supports razer devices. 

In terms of your keyboard, razer-macos supports the Ornat**a** Chroma (ends in "a," not "e") with product id 0x021e. I checked every keyboard razer-macos supports and none of have a product id of 0x7603. Lastly, the vendor id is not Razer. Your keyboard does not appear to be genuine Razer.

**Comment by Kief5555** [comment]
> Continuation of #479
> 
> > Hey, I tried that already. Didn’t work. I have the Razer Ornate Chroma. And the MSI DS100 Gaming Mouse.
> 
> Your mouse won't appear as razer-macos only supports razer devices.
> 
> In terms of your keyboard, razer-macos supports the Ornat**a** Chroma (ends in "a," not "e") with product id 0x021e. I checked every keyboard razer-macos supports and none of have a product id of 0x7603. Lastly, the vendor id is not Razer. Your keyboard does not appear to be genuine Razer.

It has the Razor Logo tho.. (For mouse)

**Comment by Kief5555** [comment]
> Continuation of #479
> 
> > Hey, I tried that already. Didn’t work. I have the Razer Ornate Chroma. And the MSI DS100 Gaming Mouse.
> 
> Your mouse won't appear as razer-macos only supports razer devices.
> 
> In terms of your keyboard, razer-macos supports the Ornat**a** Chroma (ends in "a," not "e") with product id 0x021e. I checked every keyboard razer-macos supports and none of have a product id of 0x7603. Lastly, the vendor id is not Razer. Your keyboard does not appear to be genuine Razer.

Are you able to add it? (Keyboard?, Possibly mouse?)

**Comment by WrathofthePast** [comment]
> > Continuation of #479
> > > Hey, I tried that already. Didn’t work. I have the Razer Ornate Chroma. And the MSI DS100 Gaming Mouse.
> > 
> > 
> > Your mouse won't appear as razer-macos only supports razer devices.
> > In terms of your keyboard, razer-macos supports the Ornat**a** Chroma (ends in "a," not "e") with product id 0x021e. I checked every keyboard razer-macos supports and none of have a product id of 0x7603. Lastly, the vendor id is not Razer. Your keyboard does not appear to be genuine Razer.
> 
> It has the Razor Logo tho.. (For mouse)

It's supposed to have a completely different logo on it (see pics below). MSI is a different brand from Razer. If it has the Razer logo & is advertised as MSI, it's clearly a knockoff. 



> > Continuation of #479
> > > Hey, I tried that already. Didn’t work. I have the Razer Ornate Chroma. And the MSI DS100 Gaming Mouse.
> > 
> > 
> > Your mouse won't appear as razer-macos only supports razer devices.
> > In terms of your keyboard, razer-macos supports the Ornat**a** Chroma (ends in "a," not "e") with product id 0x021e. I checked every keyboard razer-macos supports and none of have a product id of 0x7603. Lastly, the vendor id is not Razer. Your keyboard does not appear to be genuine Razer.
> 
> Are you able to add it? (Keyboard?, Possibly mouse?)

No for the mouse, but maybe for the keyboard. Send a picture of the keyboard, it's possible that it could use the same drivers.
![image](https://user-images.githubusercontent.com/75559873/146690304-bc1cca06-c8af-4ce6-a60c-84c170f3ee51.jpeg)
![image](https://user-images.githubusercontent.com/75559873/146690320-d8bbd1e9-c705-42b8-971e-9a08a56a4efd.jpeg)

**Comment by Kief5555** [comment]
Oh, I just realized, because the keyboard given to me I didn't realize it was a MSI keyboard. Sorry for wasting your time. Do you know any MSI Software that is on mac?
