### ISSUE TITLE
v4.8 not recognizing Huntsman V2 TKL as a device

### ISSUE THREAD

**Issue by dwinderberkey** [1kc/razer-macos#528]
I recently got the huntsman V2 and for some reason I cannot get the program to recognize it as a device. I have factory reset the keyboard, installed v4.6 and v4.7, restarted each time and refreshed the device list. The only 2 outstanding issues might be that I am running Monterey 12.1, and that the program does not support the huntsman V2 TKL.

Any suggestions? Thanks in advance!

**Comment by codepushr** [comment]
Same here. TKL seems not supported yet, can anyone confirm?

**Comment by jameskip** [comment]
Bump. I am having this same issue.

MacBook Pro
MacOS Monterey
M1 Max

**Comment by WrathofthePast** [comment]
Duplicate of #459
