### ISSUE TITLE
[Feature] Add custom brightness to keyboard/mouse

### ISSUE THREAD

**Issue by siavashta** [1kc/razer-macos#535]
Currently, we can set 0/100 for the brightness. I would like to be able to set a custom brightness [0,100]

**Comment by dhobi** [comment]
Can't you set the brightness with a slider [from 0 to 100%] once you have "selected" the device?

**Comment by stahmureszadeh-r7** [comment]
oh, i didn't know there is a slider when you select the device. closing it now.
