### ISSUE TITLE
[Bug] App does not read the brightness correctly

### ISSUE THREAD

**Issue by siavashta** [1kc/razer-macos#536]
The state manager debug section does not read the brightness correctly. When the brightness is not set to 100%, the state is always read as 0.

**Comment by dhobi** [comment]
Just to make sure we are on the same page: the debug section of the state manager prints out the last known values which have been set by Razer macOS. It does not update its values when changes have been made externally to a device (brightness key shortcuts, changes by other programs, ...).

So, if you change the brightness with Razer macOS and the state manager does not show this change, it's a bug. Can you confirm this (buggy) behavior?

**Comment by stahmureszadeh-r7** [comment]
I had expected to see the brightness changes even though if it's done externally. I do see the changes to the brightness when I do it through the app. So, if that's the expected behavior I am happy to close this issue.
