### ISSUE TITLE
Basilisk V3 Support

### ISSUE THREAD

**Issue by landoncrabtree** [1kc/razer-macos#539]
Any plans for support for the Basilisk V3? It doesn't show up on my list of devices.

**Comment by fgreinacher** [comment]
I guess this needs https://github.com/openrazer/openrazer/issues/1610 first?

**Comment by CevinEichnau** [comment]
is merged now :D

**Comment by landoncrabtree** [comment]
openrazer now supports Basilisk V3.

**Comment by ole-emil** [comment]
Indeed, would love support for Basilisk v3 in razer-macos

**Comment by CevinEichnau** [comment]
i saw there is already a pr for this: https://github.com/1kc/razer-macos/pull/463

**Comment by Theorian** [comment]
I could be wrong, but I just compiled from source, and it works. I downloaded the latest release, and it doesn't seem to be there in the release yet.

**Comment by JoanaRoqueOS** [comment]
Hi guys. any changes about the supporting of the basilisk v3? I just bought it yesterday and discover the incompatibility with macOS... I have a macbook pro from 2018 with macOS Monterey version 12.2.1.

I installed the app, but the mouse is not recognized... i already did multiple times the 'refresh device list' and nothing... restarted the mac to see if it makes a difference, and nothing.... But then i discover that this 'issue' was open... Any news about when you will be able to got it to work with the app???
I'm really appreciate your hard work guys!

**Comment by WrathofthePast** [comment]
While this is a duplicate of #464 and came after, this issue contains comments while the original does not, so I think this one should remain and the other should be closed.

**Comment by EV-drivechain** [comment]
Basilisk V3 is not recognized 

Installed 0.4.8 and attempted to 'refresh device list' multiple times, however the app fails to recognize the device. 
I have also moved the Basilisk mouse to different ports on MacBook Pro (2021, 14-inch, M1 Pro) running Monterey 12.2.1 and the issue persists.

**Comment by WrathofthePast** [comment]
> Basilisk V3 is not recognized
> 
> Installed 0.4.8 and attempted to 'refresh device list' multiple times, however the app fails to recognize the device. I have also moved the Basilisk mouse to different ports on MacBook Pro (2021, 14-inch, M1 Pro) running Monterey 12.2.1 and the issue persists.

Support is not yet added. PR #463 adds support.

**Comment by joshbtdev** [comment]
Hi folks! Since the Basilisk V3 hasn't been added to  the most recent release would anyone be able to point me in the right direction of a pre-compiled version which includes the V3 support? Or even if someone could point me toward a current branch I could compile that has the V3 support and I can try to figure out how to compile the source (total noob here). Thanks!

**Comment by brettwebb9498** [comment]
I can also confirm that the latest release does not support the Basilisk V3.
