### ISSUE TITLE
Feature Request: Device Selection

### ISSUE THREAD

**Issue by ericrbalch** [1kc/razer-macos#55]
When you have multiple supported devices connected, I can only see and control the first detected.

I have a Blackwidow Chroma v2, Orbweaver Chroma, and Ouroboros  Mouse connected but the UI only shows the Blackwidow.  If I unplug the Blackwidow, then I see only the Orbweaver.  If I then unplug the Orbweaver, I can see the Ouroboros.

The request here is to be able to see all supported devices connected and have the ability to select the device or devices (via checking or unchecking the device in the menu) to send the selected chroma config command to. 

Looking at the code it would seem the design is to show all the devices however even then it looks like only one "keyboard device" is supported at one time.  This seems like an artificial limitation.

**Comment by dhobi** [comment]
With v0.3.7+, all devices are shown in the menu. Please reopen / create a new issue if that is not the case for you.
