### ISSUE TITLE
DeathAdder Chroma recognized, but wont light up

### ISSUE THREAD

**Issue by mywhitenoise** [1kc/razer-macos#550]
BlackWidow Chroma is working fine, but my DeathAdder mouse isn't lighting up. Using Big Sur 11.2.3 on a Haswell.
![Screen Shot 2022-01-22 at 7 32 43 AM](https://user-images.githubusercontent.com/98224816/150645160-ddf703be-ef1f-46e9-bec0-c4a29482285e.png)

**Comment by WrathofthePast** [comment]
What happens when click on its name on the dropdown menu? I opened a PR to fix it, so if we can troubleshoot quickly, the fix can be in the next release.

**Comment by mywhitenoise** [comment]
Here you go  
![Screen Shot 2022-01-22 at 2 59 55 PM](https://user-images.githubusercontent.com/98224816/150658126-d7b36b14-4545-429e-9c53-3f8a2fe0cebc.png)

**Comment by WrathofthePast** [comment]
I'm happy it's fully populated. I found the problem though. Whoever added support originally, missed adding it to razermouse_driver.c on the backend. Because the frontend was correct, razermouse_driver.h, & razerdevice.c had it, you could see everything while nothing worked.

Before I do this, what's the max polling rate according to Razer? I need to verify as if it's **less than** 1000Hz, I'll have to manually code that in razermouse_driver.c as well. Razer-macos assumes the maximum the mouse can do is 1000Hz.

**Comment by mywhitenoise** [comment]
From what I've gathered, the max polling rate should be 1000Hz. Thank you for looking into this!
https://www2.razer.com/eu-en/gaming-mice/razer-deathadder-chroma

**Comment by WrathofthePast** [comment]
I've been looking into this. Apparently, there's a lot of old mice with the same issue. I'm not sure how it happened and I'm surprised this wasn't noticed before. I'll work on this more later as the old Razer mice often have quirks with them (like no red for example), so I have to look what openrazer did.

**Comment by WrathofthePast** [comment]
> BlackWidow Chroma is working fine, but my DeathAdder mouse isn't lighting up. Using Big Sur 11.2.3 on a Haswell.
> ![Screen Shot 2022-01-22 at 7 32 43 AM](https://user-images.githubusercontent.com/98224816/150645160-ddf703be-ef1f-46e9-bec0-c4a29482285e.png)

What version of razer-macos did you have this bug on? If it was v0.4.8, #552 will fix it and I suggest trying an earlier version. If you had this bug on multiple versions or a version earlier than v0.4.8, this may still fix it. Regardless, this PR fixes at least 1 bug with the DeathAdder Chroma.

**Comment by mywhitenoise** [comment]
I'm on v0.4.8, I can try an older version...but also interested in applying the fix mentioned in #552, but I'm not sure on how to apply it.

**Comment by WrathofthePast** [comment]
Unfortunately, as I describe in #558, I cannot compile at this time. You'll have to try an older version until Apple fixes that bug.

**Comment by Urshii** [comment]
unfortunatelly, it's not working for v0.4.8 and v0.4.7 too :(

**Comment by WrathofthePast** [comment]
> unfortunatelly, it's not working for v0.4.8 and v0.4.7 too :(

That's unfortunate, but it maybe still be fixed with #552. However, I can't provide a test build at this time due to #558. Once that's resolved, I'll provide a test build to see if that fixes it.

**Comment by Urshii** [comment]
> > unfortunatelly, it's not working for v0.4.8 and v0.4.7 too :(
> 
> That's unfortunate, but it maybe still be fixed with #552. However, I can't provide a test build at this time due to #558. Once that's resolved, I'll provide a test build to see if that fixes it.

Is there any way that you could link a tutorial for applying #552 by myself, or test build for apple silicon? I can test it on both M1 and intel processor, if that will help the case to move forward (I have both mac mini m1 and macbook pro 2017)

**Comment by Urshii** [comment]
With a little help I was able to build version on M1 with #552 but it seems that it's not resolving a problem. I also checked mouse on synapse 2 on windows and lightning is working, so it's not a hardware issue. Any other ideas why it's not working?

**Comment by WrathofthePast** [comment]
> With a little help I was able to build version on M1 with #552 but it seems that it's not resolving a problem. I also checked mouse on synapse 2 on windows and lightning is working, so it's not a hardware issue. Any other ideas why it's not working?

Good job for figuring out how to do that on your own. I thought I was able to package x64 and arm64 builds, but when I went to open them, the program was bricked.

To answer your question: does the mouse have multiple profiles? If so, make sure it's set to the white one. Did you try pressing `Refresh Device List`? Also, it sounds like you may have profile(s) configured in `State Manager`. You can change the triggers for it there or preferably and regardlessly, try `Clear all settings` if you don't mind losing them. Make sure you try these on build you made using #552.
