### ISSUE TITLE
Razer Baslisk X Hyperspeed

### ISSUE THREAD

**Issue by JayKayDude** [1kc/razer-macos#554]
So my Razer Baslisk X Hyperspeed won't show up on the devices list and I am connecting through Bluetooth and I am not sure if it's just that or it's not in the registered in the app. Please fix

**Comment by WrathofthePast** [comment]
Duplicate of #497

**Comment by JayKayDude** [comment]
But its still not working even with dongle

**Comment by JayKayDude** [comment]
<img width="277" alt="Screen Shot 2022-01-25 at 3 41 44 PM" src="https://user-images.githubusercontent.com/95384723/151072265-8530e722-7b6e-4241-acd4-f013b1ef61a7.png">
