### ISSUE TITLE
Razer X Hyperspeed

### ISSUE THREAD

**Issue by JayKayDude** [1kc/razer-macos#555]
Soo when I connect with dongle or Bluetooth it won't show anything
<img width="277" alt="Screen Shot 2022-01-25 at 3 41 44 PM" src="https://user-images.githubusercontent.com/95384723/151073645-0f9622d5-0e58-4f33-aad5-08c82b8ad095.png">
<img width="183" alt="Screen Shot 2022-01-25 at 3 59 05 PM" src="https://user-images.githubusercontent.com/95384723/151073990-642e7e78-64aa-44b8-92ef-9a2dada1d561.png">
I tried to look at different posts about it but its not helping at all soo I need help

**Comment by WrathofthePast** [comment]
Did you try the latest test build? It should say v04.8test7 in `About`.

**Comment by JayKayDude** [comment]
> Did you try the latest test build? It should say v04.8test7 in `About`.

No but let me look

**Comment by JayKayDude** [comment]
no actually I did download the latest one

**Comment by JayKayDude** [comment]
unless you made a new version

**Comment by WrathofthePast** [comment]
Actually, I just did because I found the bug.

**Comment by WrathofthePast** [comment]
> Actually, I just did because I found the bug.

Here's a new [version](https://github.com/WrathofthePast/razer-macos/releases/tag/v0.4.8-test8) to test. Let me know if everything works now specifically for receiver mode. If bluetooth mode works too, let me know as well, but odds are it won't as openrazer doesn't support bluetooth.

**Comment by JayKayDude** [comment]
ok

**Comment by JayKayDude** [comment]
ok I tested with Bluetooth and still no luck but i will try with dongle later today but thanks for trying to fix the problem.

**Comment by WrathofthePast** [comment]
> ok I tested with Bluetooth and still no luck but i will try with dongle later today but thanks for trying to fix the problem.

Thank you for testing. The Basilisk X Hyperspeed isn't supported yet; hence, why these are test builds.

**Comment by JayKayDude** [comment]
so it did work with the dongle but nothing is showing up and not sure what to do.
<img width="492" alt="Screen Shot 2022-01-26 at 6 43 01 PM" src="https://user-images.githubusercontent.com/95384723/151276501-41585889-39da-480f-9361-774c6de85e64.png">

**Comment by WrathofthePast** [comment]
You don't have to do anything. I'm speaking to openrazer about this and they've provided some insight. I'll provide a new test release soon.

Apparently, the OS constantly asks for the charging status of any mouse with a battery, but because the Basilisk X Hyperspeed uses nonrechargable batteries, it doesn't answer resulting in the program crashing. The solution is to spoof the charging status to not charging, so the OS stops asking.

**Comment by WrathofthePast** [comment]
Here's a new [test release](https://github.com/WrathofthePast/razer-macos/releases/tag/v0.4.8-test9). Let me know if receiver mode works as intended now. Also let me know if bluetooth works now as well.

**Comment by JayKayDude** [comment]
ok let me see

**Comment by JayKayDude** [comment]
ummm so the Bluetooth on mine is acting weird so i'm using the adapter and it pops up but when i clicked on it, the screen turned just black and nothing is responding

**Comment by JayKayDude** [comment]
so basically its the exact problem. and btw i will see if i can fix my bluetooth and test it

**Comment by rtvt** [comment]
Any news guys?
Just bought Basilisk X Hyperspeed, and face same problem. Is there any way to make work:
1. By Bluetooth?
2. By dongle

**Comment by JayKayDude** [comment]
no sadly we talked about it more here for more info: #560
