### ISSUE TITLE
Software doesn't recognize Huntsman V2 TKL (works for DeathAdder V2)

### ISSUE THREAD

**Issue by hulejman** [1kc/razer-macos#561]
Hello, basiclly, software doesnt recognize Huntsman V2 TKL. It it not listend in devices and whereever I click to change RGB effects, it doesnt work for it. It does work for Deathadder V2 tho.

**Comment by jameskip** [comment]
Same here. In MacOS.

**Comment by WrathofthePast** [comment]
Duplicate of #459
