### ISSUE TITLE
Would like to build additional features - just need some quick guidance 

### ISSUE THREAD

**Issue by joshuagrzech** [1kc/razer-macos#570]
Yooooo - I'm a software engineer that was just gifted a Blackwidow chroma, and want to be able to statically set colors _per key_ , as well as explore some custom animations. I'll do all the work, just trying to get an idea of where to start. Are drivers and everything ported from open-razer to the point where I can just write a UI with some JS, or would it be a bit deeper? I'm wanting to mimic functionality of [razer-genie](https://github.com/z3ntu/RazerGenie)

**Comment by WrathofthePast** [comment]
> Yooooo - I'm a software engineer that was just gifted a Blackwidow chroma, and want to be able to statically set colors _per key_ , as well as explore some custom animations. I'll do all the work, just trying to get an idea of where to start. Are drivers and everything ported from open-razer to the point where I can just write a UI with some JS, or would it be a bit deeper? I'm wanting to mimic functionality of [razer-genie](https://github.com/z3ntu/RazerGenie)

That's great to hear. I'm adding new features right now as a matter of fact. To answer your questions, please review the Wiki tab and note that all the drivers are on the backend in the submodule `librazermacos`. If you need any more information or if you'd like to assist with the new features I'm adding, let me know.
