### ISSUE TITLE
Support for Brightness/turn light off with display standby/turn light off after inactivity.

### ISSUE THREAD

**Issue by firecaste** [1kc/razer-macos#60]
This software is awesome so thankyou cause it saved my ass after buying a mamba wireless and finding it dosent support MacOS properly.

It would be really handy to have brightness control of the light and the ability to turn the light off after periods of inactivity or turn off light when monitor goes into standby just like synapse has.

Thanks again :)

**Comment by 1kc** [comment]
Glad it was useful! I think brightness control is possible to add in the future.

**Comment by firecaste** [comment]
That would be super super handy! Would defo give us the final piece of lighting functionality synapse has options for on the mice :)

**Comment by bb1234cp** [comment]
Completely agree with that suggestion! That’d be so useful.

**Comment by theanorak-keith** [comment]
Adding thanks for this tool -- and also endorsing any enhancements you could make to control both brightness AND transition speed for any of the non-static lighting effects. Cheers!

**Comment by 1kc** [comment]
Brightness control for keyboard had just been added.
The turn off and on while sleeping ideas is pretty cool.

**Comment by dhobi** [comment]
Let's track the "sleeping idea" here #122
