### ISSUE TITLE
Please add support for mouse Razer Viper Mini

### ISSUE THREAD

**Issue by iSoftpedia** [1kc/razer-macos#63]
I love this Mouse, very want to see it in the list of supported devices =)

**Comment by iSoftpedia** [comment]
![Screenshot 2020-09-28 at 13 09 31](https://user-images.githubusercontent.com/37078829/94419871-007a5b00-018c-11eb-88ef-44d5d53f0e8f.png)

**Comment by 1kc** [comment]
I have just added the Viper Mini in the new release: https://github.com/1kc/razer-macos/releases/tag/v0.2.5
Please test it and let me know how it goes.

**Comment by david92rl** [comment]
> I have just added the Viper Mini in the new release: https://github.com/1kc/razer-macos/releases/tag/v0.2.5
> Please test it and let me know how it goes.

Hey @1kc , thanks for supporting Viper Mini. I just tested the latest release (0.2.6) it and it doesn't seem to detect it. 
I installed following the instructions (moving to Apps directory, allowing it on Security Preferences). I've also tried restarting.
I'm connecting the mice through an USB hub, See attached images:

<img width="233" alt="Screenshot 2020-10-09 at 12 55 38" src="https://user-images.githubusercontent.com/19664410/95575482-0e9f6580-0a2f-11eb-85cf-33fbd28c0b61.png">
<img width="389" alt="Screenshot 2020-10-09 at 12 56 26" src="https://user-images.githubusercontent.com/19664410/95575497-13fcb000-0a2f-11eb-90d8-631ae6353c39.png">

**Comment by 1kc** [comment]
Thanks for reporting this @david92rl , I just identified the bug built a new dmg. Could you give this a shot and tell me what you see? All colour effects should be working.

https://github.com/1kc/razer-macos/releases/tag/v0.2.6-fixed

**Comment by david92rl** [comment]
Thanks for the quick response.
Still nothing, I've even tried restarting multiple times, unplugging, different ports...

**Comment by 1kc** [comment]
Sorry I might have forgotten to recompile the C driver code when I rebuilt it. Fingers crossed it works this time.
The new file has been uploaded here: https://github.com/1kc/razer-macos/releases/tag/v0.2.6-fixed

**Comment by david92rl** [comment]
Working now! Nice one @1kc

**Comment by 1kc** [comment]
Awesome, do all the different colour effects work?

**Comment by iSoftpedia** [comment]
> Awesome, do all the different colour effects work?

Yes, all work, big thanks! In the review razer viper mini will show this program on youtube) One more question, is it possible to make a breath effect with one custom color? now the breathing effect shimmers with all colors, it is not adjustable. Is it possible to bind the choice of color to the breath like in other modes?

**Comment by 1kc** [comment]
Great! I wasn't aware the app was in a Youtube video 😄

is it possible to make a breath effect with one custom color?
Hopefully this can be added in the future. Like in openrazer below.
![image](https://user-images.githubusercontent.com/20840688/97080830-a44b0f80-1641-11eb-84a5-9f1036924074.png)

Closing the issue for now since it seems like Razer Viper Mini is now supported.
