### ISSUE TITLE
`napi.h` not found

### ISSUE THREAD

**Issue by L1cardo** [1kc/razer-macos#69]
![image](https://user-images.githubusercontent.com/33802186/95660821-11987400-0b5d-11eb-8389-5b410ca7898a.png)

**Comment by 1kc** [comment]
This compiles fine for me by just running `yarn` on a newly cloned repository? I am using VS Code.

**Comment by L1cardo** [comment]
I want to build an app that only  indicates battery info using your drivers.
Maybe `napi` is an electron thing?

**Comment by 1kc** [comment]
Yes, napi is used by Electron to call the C driver code. You can refer to https://github.com/dylanparker/osx-razer-led if you want to build apps without the Electron frontend. Just copy the drivers across from this project.

**Comment by L1cardo** [comment]
> Yes, napi is used by Electron to call the C driver code. You can refer to https://github.com/dylanparker/osx-razer-led if you want to build apps without the Electron frontend. Just copy the drivers across from this project.

Thanks!
Actually razed-macos is a great project, but I just want to know the battery info of my mouse. And electron makes the app a little huge.

**Comment by 1kc** [comment]
Thanks! I agree, for displaying batter info Electron is probably a bit too heavyweight.
Electron is used in this project mostly because its easier for us web developers to build new features quickly, rather than having to learn Swift.

**Comment by L1cardo** [comment]
I know some swift but know nothing about c, so this is a nightmare for me.
Anyway thanks!

**Comment by 1kc** [comment]
Yes C can be challenging. Let me know if you need help navigating the codebase

**Comment by L1cardo** [comment]
OK, I quit, really don't know anything about C.

**Comment by 1kc** [comment]
I can feel your pain 😭. C is defintely not beginner friendly.

**Comment by L1cardo** [comment]
> I can feel your pain 😭. C is defintely not beginner friendly.

Haha, then I just use you project instead of making my own, it's OK.
Thanks!
