### ISSUE TITLE
Unable to detect devices even with refresh

### ISSUE THREAD

**Issue by geo-rge-li** [1kc/razer-macos#748]
System Details:
MacOS Monterey 12.6.1
Apple M1 Max
Devices are Razer Blackwidow v3 Mini Wireless and Basilisk v3 Pro paired to a single hyperspeed dongle (in this case it's the one that came with the mouse)

When I dragged and dropped v0.4.10, I did not get the expected security prompt. The devices list appeared empty. I clicked refresh and no devices showed up. Also tried versions as far back as 0.4.6.

**Comment by EnVisione** [comment]
How did you connect it to a single dongle?

**Comment by geo-rge-li** [comment]
> How did you connect it to a single dongle?

I did so using Synapse's Pairing Utility on my Windows machine. I swap to MacOS for work and use Windows on a personal device.

**Comment by geo-rge-li** [comment]
So I did manage to get it working and forgot to post. Basically, I went back to using the original dongle for the keyboard and also performed a firmware update on a Windows machine to the 2.x version of the firmware and it worked.
