### ISSUE TITLE
can someone tell me if Bassilisk Ultimate's wave effect works? im buying one

### ISSUE THREAD

**Issue by EDWINTEGOD** [1kc/razer-macos#76]

**Comment by 1kc** [comment]
I think some of the other guys have got it to work, haven't tested personally though. 

See: https://github.com/1kc/razer-macos/commit/d95229e01283814ea80843b0c1e9d8c81e5c40a0

If it doesn't work as well as you expect, you can always return it?

**Comment by EDWINTEGOD** [comment]
ok thanks! i've got one coming tomorrow so i hope it does well!

**Comment by 1kc** [comment]
Did it work well?

**Comment by EDWINTEGOD** [comment]
it worked great! thanks again for making this awesome piece of software!
