### ISSUE TITLE
Razer Blackwidow Lite works in macOS (MacBookPro)

### ISSUE THREAD

**Issue by rvignolo** [1kc/razer-macos#77]
Hi! 

Sorry to bother you, but I would like to buy a Razer Blackwidow Lite keyboard ([this](https://www.razer.com/gaming-keyboards/razer-blackwidow-lite/RZ03-02640200-R3U1) one) and before that, I need to know if it works in macOS Catalina (eventually in Big Sur). 

Thank you in advance!

**Comment by EDWINTEGOD** [comment]
everything that is on that list works in big sur. i'm stuck on dev beta 1 and can't update but all of the devices work great.

**Comment by rvignolo** [comment]
Hi @EDWINTEGOD,

the list mentions Razer Blackwidow 2019 and Elite, but not the Razer Blackwidow **_Lite_**, which is different. That is why I am asking. Thank you!

**Comment by EDWINTEGOD** [comment]
oh, yeah. Sry. idk if it works

**Comment by 1kc** [comment]
Hi @rvignolo The Blackwidow Lite should be supported. However that keyboard doesn't have Chroma, so I am not sure what you would use the app for?
I'll try to implement brightness changes in the future though.

See: https://github.com/1kc/razer-macos/blob/031cb6c29222992d2cb2f2a92c9d731c43434324/src/driver/razerkbd_driver.h#L57

> everything that is on that list works in big sur. i'm stuck on dev beta 1 and can't update but all of the devices work great.

Thanks thats good to know @EDWINTEGOD

**Comment by rvignolo** [comment]
Hi @1kc! Thanks for your reply!

I was thinking about brightness and and also about key effects (I have no idea if these two things can be configured using a combination of keys in the keyboard). 

Also, what about changing key functions, this can be accomplished using Karabiner-Elements and has nothing to do  with razer-macos?

Thank you!

**Comment by 1kc** [comment]
Yes, this app is mostly used to change colour effects for keyboard and mouse.
Karabiner-Elements is good for chaging the key bindings. Although im quite used to the way it is now for PC-style keyboards.

The list in the readme file shows the list of keyboards that we have actually physically tested.

Looks like you won't be needing this then, good luck anyways!
