### ISSUE TITLE
Razer Goliathus 3xl mousepad - need to be added.

### ISSUE THREAD

**Issue by joffe1** [1kc/razer-macos#777]
Cannot change RGB colors on MacOs by using Razer Goliathus 3xl mousepad.

**Comment by joffe1** [comment]
Updated code:
- added new device for support -> build -> codesign 
- run updated .dmg file from .dist and replace it with your current Razer-Macos app from application folder.

Thats it. EzPz.

If you need a help, contact me ;)

**Comment by OmranK** [comment]
@joffe1 I'm trying to control the color of my Goliathus 3xl. Does not look your changes were merged in (or the latest release doesn't include your changes)

That means I need to check out your fork and build the .dmg ? Can you please explain in detail how I can do this?

**Comment by joffe1** [comment]
Maybe they just didnt added my changes. Try to find one of the model which already exist in code and dublicate same things for Razer Goliathus 3xl model. @OmranK

**Comment by OmranK** [comment]
@joffe1 I checked out your fork but I'm not sure how to get an executable from it. Do you know how?
