### ISSUE TITLE
Can you add support for the razer mamba elite and firefly v2

### ISSUE THREAD

**Issue by JapeTheGrape** [1kc/razer-macos#78]
The razer mamba elite works but not with all the setting it’s only available with wave for the moment.

**Comment by 1kc** [comment]
That looks like a fully feature mouse with a lot of colour options. Might look into it in the future.

**Comment by luchian94** [comment]
What about firefly v2? should be faster to implement.
Got it few days ago but can't use it :(

**Comment by dhobi** [comment]
Firefly V2 should be supported by now. Best would be to create a new issue with a description which exact features of Mamba Elite you are missing in razer-macos.
