### ISSUE TITLE
support/question

### ISSUE THREAD

**Issue by Tochey** [1kc/razer-macos#79]
Not an issue at all but is there an expected release date for support on the Razer Huntsman Mini?

**Comment by 1kc** [comment]
It is still being worked on upstream https://github.com/openrazer/openrazer/issues/1230, so I am not entirely sure

**Comment by sourav-dey** [comment]
Can you please run 
lsusb | grep '1532:'

and get the output?
We can add that device id to the keyboard list and it will just work. 

If we wait for openrazer to get it working first, then it will take a lot of time. They still don't have Basilisk Ultimate support which this project has already.

**Comment by sourav-dey** [comment]
Looks like it is:
Bus 001 Device 003: ID 1532:0257 Razer USA, Ltd Razer Huntsman Mini

We will just add that to the keyboard list, but you need to test it out. @Tochey

**Comment by Tochey** [comment]
My device doesn't show up on the device list, it didn't work

**Comment by sourav-dey** [comment]
@Tochey How did you try? Did you clone the repo and add the pull request and ran?

**Comment by Tochey** [comment]
I cloned the repo but have no idea how to run

**Comment by Tochey** [comment]
cloned the repo but have no idea of how to run it

**Comment by Tochey** [comment]
update I figure out how to run it via command line, got the dmg file, installed and it connected to my device. But the I am not able to change colors or use the functionalities.
<img width="275" alt="razer" src="https://user-images.githubusercontent.com/54341970/97384546-479c5e80-18a6-11eb-93d7-967d094c9932.png"> @sourav-dey

**Comment by dhobi** [comment]
Huntsman Mini progress is tracked in #107.
