### ISSUE TITLE
Razer Basilisk V3 Pro? --- I could have missed it. 

### ISSUE THREAD

**Issue by adaptivephase-io** [1kc/razer-macos#790]
Would love to know if this will work with Razer Basilisk V3 Pro... I very well could have overlooked it. I tried running and I cannot get my device to be detected and I do not see "Razer Basilisk V3 Pro" in the compatible  list.

**Comment by andriinb** [comment]
Basilisk V3 Pro here, not working 
Basilisk V3 Pro
1532:00AA 
1532:00AB
looks like drivers already exist @ https://github.com/openrazer/openrazer/tree/master/driver

**Comment by adaptivephase-io** [comment]
ah I see and I overlooked this conversation --> https://github.com/1kc/razer-macos/issues/778
