### ISSUE TITLE
Application?

### ISSUE THREAD

**Issue by Razerviper** [1kc/razer-macos#82]
I am a mac user and annoyed at razer for not doing synapse 3 like all the rest of us here. I game on hypixel.net on minecraft.
Wondering if it's just on the menu bar at the top, or an application like synapse 2 for example.
If it isn't, maybe release an application that's like synapse 2 but with fewer bugs and more synapse 3?
Thank you
P.S is openrazer.github.io/#devices all the ones that are supported? and does this work with High Sierra and Mojave?
Edit: Does it work with Razer Kraken X

**Comment by dhobi** [comment]
Razer macOS is mainly a tray app for now. Who knows, maybe this will change in the future?
Razer Kraken X is tracked in your other issue #85 . I'll close this for now.
