### ISSUE TITLE
Can you please add support for Razer Basilisk V2?

### ISSUE THREAD

**Issue by EnimaTek7** [1kc/razer-macos#87]
Razer Basilisk Ultimate is already supported, so maybe it's also easy to add support for Razer Basilisk V2.

**Comment by bbedevian** [comment]
Seconding this! Currently working with my huntsman tournament ed but not recognizing basilisk v2

**Comment by sourav-dey** [comment]
Hi @bbedevian and @xDedication7x ,
Can you guys please checkout https://github.com/sourav-dey/razer-macos master and try to run it?
I added Basilisk V2 support but I don't have a Basilisk V2 mouse to test it out.

You can find the way to run here: https://github.com/sourav-dey/razer-macos/blob/master/README.md#developer-usage

Once you confirm it works, I will merge it to this repo.

Thanks,
Sourav

**Comment by bbedevian** [comment]
I forked and cloned the repo. Ran yarn to install dependencies, then ran yarn dev, getting a compile error re: 'react-slider' in mouse sensitivity

**Comment by bbedevian** [comment]
ooh, strangly though, i have 4 of your icons in my top bar and one of them recognizes the mouse

**Comment by bbedevian** [comment]
<img width="1440" alt="Screen Shot 2020-11-30 at 7 31 16 PM" src="https://user-images.githubusercontent.com/60368812/100681822-9f653400-3342-11eb-87ee-7f70a710a87d.png">

**Comment by sourav-dey** [comment]
Sorry about that. I was missing a component. Please pull again and run it.

**Comment by sourav-dey** [comment]
Please Check if it detects and after detection, please do check if any one of the effects like wave work.

**Comment by bbedevian** [comment]
confirming the updated code works and the different effects do too!

**Comment by sourav-dey** [comment]
Awesome. Thanks for testing @bbedevian 
I will merge it into the main branch.

**Comment by bbedevian** [comment]
No Problem, thank YOU!

**Comment by xDedication7x** [comment]
Sorry I'm late to the party. I just downloaded the latest release version 0.3.1 but my Basilisk V2 is not detected. Razer BlackWidow Elite and Goliathus Chroma Extended are detected and I already tried unplugging my Goliathus, but Basilisk V2 is still not detected :(

**Comment by StevenBoelhouwer** [comment]
> Sorry I'm late to the party. I just downloaded the latest release version 0.3.1 but my Basilisk V2 is not detected. Razer BlackWidow Elite and Goliathus Chroma Extended are detected and I already tried unplugging my Goliathus, but Basilisk V2 is still not detected :(

Same for me! Maybe we need to wait for 0.3.2 and it just missed the release?

**Comment by joerg-wille** [comment]
Basilisk V2 is not working in any releases.
But the [commit "fixing package"](https://github.com/sourav-dey/razer-macos/commit/ab8255bcfbb45c0f3bc4ea750f1920884bbbc60e) from Sourav is indeed working.
I created a [pull request](https://github.com/1kc/razer-macos/pull/227) with a fix.
@1kc after testing you can close issues [87](https://github.com/1kc/razer-macos/issues/87) [221](https://github.com/1kc/razer-macos/issues/221).
@sourav-dey Thanks for adding the support for Basilisk V2.

**Comment by 1kc** [comment]
Will do later today!

**Comment by wortkrieg** [comment]
I can confirm: this fix works :)

**Comment by xDedication7x** [comment]
I can also confirm the fix works (partially). Basilisk V2 is now detected and shown in the menu. When I select _Spectrum All Devices_ or _Cycle All Devices_ the mouse changes the color synchronized with all my other devices, but when only change the color of the mouse (e.g. Static - White) the mouse does not change it's color (changing color of all other devices works)

**Comment by WrathofthePast** [comment]
Basilisk V2 is supported. Can this issue be closed?

**Comment by joerg-wille** [comment]
I have only tested the version with my [pull request](https://github.com/1kc/razer-macos/pull/227), which worked for me.
But as @EnimaTek7 and @wortkrieg confirmed it, I think we can close this issue!

**Comment by EnimaTek7** [comment]
Yes, I‘m currently using version 0.4.5 and it works perfectly, thanks again 🙂
