### ISSUE TITLE
Support for Blackwidow V3 Tenkeyless

### ISSUE THREAD

**Issue by franalt** [1kc/razer-macos#88]
Hello everyone, I was wondering if there is support for the Blackwidow V3 Tenkeyless keyboard. Its not being detected by the current build. Anyone has it working or can tell me how to add it?

![image](https://user-images.githubusercontent.com/20582332/97824408-95e0a180-1c9a-11eb-99e8-4d4853bfe0ee.png)

![image](https://user-images.githubusercontent.com/20582332/97824414-9aa55580-1c9a-11eb-96bf-562d5b3dd231.png)

**Comment by 1kc** [comment]
I don't think there is support for it upstream yet - https://github.com/openrazer/openrazer/blob/master/driver/razerkbd_driver.h.

You could still give it go by making your own custom build, see here - https://github.com/1kc/razer-macos/pull/83 for a similar device addition.

**Comment by franalt** [comment]
Thanks for pointing me on the right direction. I've added the ProductId to razerkbd_driver.h and the keyboard is successfully detected. However, changes do not apply. In the merge you pointed, I see I have specify the functions correctly in razerkbd_driver.c, is there any rule to follow or just trial an error?

**Comment by 1kc** [comment]
You will also need to add the device to `is_keyboard(IOUSBDeviceInterface **usb_dev)` function in razer-macos/src/driver/razerdevice.c 

Then you will need to add the device to colour effect setting functions under, razer-macos/src/driver/razerkbd_driver.c. 

For example in the razer_attr_write_mode_spectrum function, add a new `CASE` for the device in the switch statement for where all the other Blackwidow devices are. ie add `case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3` somewhere here:
![Screen Shot 2020-11-03 at 12 16 44 am](https://user-images.githubusercontent.com/20840688/97878084-dce99800-1d69-11eb-9b53-f565c5efad53.png)


Be sure to rebuild the drivers with `yarn rebuild` every time you change the driver code before you run it with `yarn dev`.

**Comment by franalt** [comment]
Yep, did everything and no luck, the keyboard its on its default spectrum mode.

razerdevice.c
![image](https://user-images.githubusercontent.com/20582332/97878963-197faa00-1cfe-11eb-89b5-22ba67fd5807.png)

razerkbd_driver.h
![image](https://user-images.githubusercontent.com/20582332/97878982-24d2d580-1cfe-11eb-9a15-f9757c16937b.png)

razerkbd_driver.c added for every USB_DEVICE_ID_RAZER_BLACKWIDOW_BLACKWIDOW_2019 a USB_DEVICE_ID_RAZER_BLACKWIDOW_BLACKWIDOW_v3
![image](https://user-images.githubusercontent.com/20582332/97879012-30260100-1cfe-11eb-922b-9084e8810d5e.png)

Maybe the V3 has other parameters?

**Comment by franalt** [comment]
I found this on the openrazer project: https://github.com/openrazer/openrazer/issues/1318 maybe it means something to you, I don't have much experience with drivers

**Comment by 1kc** [comment]
Yeah maybe. Hopefully Razer hasn't changed anything hardware-wise since it's a pretty recent keyboard. Typically it's straightforward to add support for new devices. I'd keep an eye out on that PR to see if there are any breakthroughs. Let me know, and I'll port the new driver changes to over here.

**Comment by Blejator90** [comment]
let me now how you go - if you need help maybe.

**Comment by ryon01** [comment]
Any word on adding support for this device yet? Just picked it up and got home to realize that Razor has disowned all of us on mac 🙃

**Comment by vikivulpix** [comment]
I'll jump on this bandwagon. HELP!

**Comment by tbremer** [comment]
So, I wanted to take a lot at this and see if I could get something working. I am able to detect the device, but none of the color changes are taking hold. I've mostly focused on Starlight (as it seems that would be the most obvious switch).

My current struggle is trying to see output from the `printf` calls. I've attached a debugger with no luck. Anyone have any suggestions?

![image](https://user-images.githubusercontent.com/2998575/100373254-18c1f700-2fd0-11eb-8146-fe68819e71e1.png)

**Comment by koffiebaard** [comment]
I have just created a PR to add support for the BlackWidow V3: https://github.com/1kc/razer-macos/pull/248

**Comment by dhobi** [comment]
For state updates on BlackWidow V3 Tenkeyless: #276
