### ISSUE TITLE
Support For Ornata V2

### ISSUE THREAD

**Issue by MrSab93** [1kc/razer-macos#89]
Hi there, can you please add support for the keyboard Razer Ornata V2? I still have 4 days to return it... I like this keyboard so much, very sad it doesn't work with my MacOS Catalina 10.15.7

When I plug the keyboard to the laptop, it lights up and the light keeps fading into different colours. However, I have no control over it and it is not being detected by your app.

Thank you so much for your efforts and amazing work!

**Comment by 1kc** [comment]
Hi,
Apologies I am a bit busy at these times.
Do you want to try adding support with your own custom build. Perhaps you could have a look at the previous commits/pull requests adding support to new devices.

On 4 Nov 2020, at 6:25 pm, MrSab93 <notifications@github.com> wrote:

﻿

Hi there, can you please add support for the keyboard Razer Ornata V2? I still have 4 days to return it... I like this keyboard so much, very sad it doesn't work with my MacOS Catalina 10.15.7

Thank you so much for the efforts and good work!

**Comment by MrSab93** [comment]
@1kc Thank you for the fast feedback! Much appreciated.

I am a fast learner. If there is any kind of tutorial that I can follow, please share it with me. I will be very happy to do that for myself. I am not an IT guy, but I can follow a step by step tutorial without any problems. 

Thanks again!

**Comment by 1kc** [comment]
You will definitely need some experience with C. I’m not sure if you can get there in a few days if you start from zero, and I don’t think there are tutorials specifically on this types of programming. Looking at the other people’s code and commits is how Ive learnt the best.

On 4 Nov 2020, at 6:59 pm, MrSab93 <notifications@github.com> wrote:

﻿

@1kc<https://github.com/1kc> Thank you for the fast feedback! Much appreciated.

I am a fast learner. If there is any kind of tutorial that I can follow, please share it with me. I will be very happy to do that for myself. I am not an IT guy, but I can follow a step by step tutorial without any problems.

Thanks again!

**Comment by mindaboveall** [comment]
Looking for this one as well. Might give dev'ing it a try myself, but like OP, my C knowledge isn't extremely strong.

**Comment by expremo** [comment]
@1kc thank you so much for this! I have a Ornata v2 too and would love to see added support in future builds! If I can help let me know.

**Comment by aheze** [comment]
I just got an Ornata V2 and it isn't being detected. Do you guys know when it will be supported?

**Comment by dhobi** [comment]
Ornata V2 should be (partly) supported in the meantime.
