### ISSUE TITLE
Add Support for Firefly V2

### ISSUE THREAD

**Issue by joxy88** [1kc/razer-macos#91]
I just downloaded the app and its fucking amazing, My basilisk and tartarus works well, Would love it if you support for firefly and maybe work on binding the keys with shortcuts, basically what synapse does would over the line. Thanks

**Comment by kennyjeffris** [comment]
Would also love firefly support

**Comment by LeeHP** [comment]
Great work on this project! I would also like Firefly V2 functionality.

**Comment by sfroment** [comment]
Hi i've added support 6 days ago, just update to https://github.com/1kc/razer-macos/tree/v0.3.0 and it should work.
@1kc can you close this issue ?

**Comment by LeeHP** [comment]
Thanks for offering this, it's great! So while my Firefly works and I can change the color, the Device is greyed out in the dropdown, not sure if that is normal or not.

**Comment by sfroment** [comment]
Hi @LeeHP if you have something similar to: 
<img width="201" alt="Screen Shot 2020-12-03 at 17 47 28" src="https://user-images.githubusercontent.com/7238385/101060347-9f0da880-358f-11eb-8ea8-003f8b07c902.png">
It's 🆗

**Comment by LeeHP** [comment]
OK, great! Thanks again and for your fast reply!

**Comment by dhobi** [comment]
This looks like a solved case. 👍  Let's close it.
