### ISSUE TITLE
OSX Big Sur Support

### ISSUE THREAD

**Issue by Gradivis** [1kc/razer-macos#97]
Hi there - thanks for this incredible app, I was about to swear off Razer for good until I found it.

I was wondering if it's safe to upgrade to Big Sur or whether that will break functionality?

Many thanks!

**Comment by gratefulsorceror** [comment]
I’m not exactly sure on the peripherals you’re using; but I’m running Big Sur on my black widow elite with no foreseeable issues, I hope though it continues this way.

**Comment by Gradivis** [comment]
> I’m not exactly sure on the peripherals you’re using; but I’m running Big Sur on my black widow elite with no foreseeable issues, I hope though it continues this way.

Thank you for confirming - by chance that's the exact keyboard I have. Much appreciated!

**Comment by lifeofmle** [comment]
Thank you so much for this project. 

I installed this on my Macbook 2019 on BigSur 11.0.1 and I am using the Razer Cynosa v2 and it works like a charm with the different colour modes and custom colours

**Comment by 1kc** [comment]
I have just built it on MacOS Big Sur as well and uploaded the release. Seems like it's working fine for others as well so I am closing this.
